INSERT INTO industry_solutions
  (id, code, name, description, status)
VALUES
  ('CBE', 'CBE', 'Construction & Built Environment',
   'NuBlox industry configuration for organisations that design, develop, construct, manufacture, manage, operate and maintain the built environment.',
   'ACTIVE');

INSERT INTO delivery_domains
  (id, industry_solution_id, code, name, purpose, sequence, status)
VALUES
('D01', 'CBE', 'D01', 'Architecture & Design', 'Architectural and interior/fit-out design workflows.', 1, 'ACTIVE'),
('D02', 'CBE', 'D02', 'Engineering & Technical Design', 'Civil, structural, building-services and specialist technical engineering.', 2, 'ACTIVE'),
('D03', 'CBE', 'D03', 'Surveying, Property & Land', 'Building, land, valuation, development and rural surveying.', 3, 'ACTIVE'),
('D04', 'CBE', 'D04', 'Commercial, Contracts & Cost', 'Estimating, quantity surveying and contract/commercial management.', 4, 'ACTIVE'),
('D05', 'CBE', 'D05', 'Geospatial, Planning & Transport', 'Planning, mapping, GIS and transport planning.', 5, 'ACTIVE'),
('D06', 'CBE', 'D06', 'Site Delivery & Construction Management', 'Site management, supervision, labour and demolition delivery.', 6, 'ACTIVE'),
('D07', 'CBE', 'D07', 'Building Trades', 'Trade work, work orders, materials, installation and snagging.', 7, 'ACTIVE'),
('D08', 'CBE', 'D08', 'Building Services Trades', 'MEP/service trades, jobs, equipment, testing and maintenance.', 8, 'ACTIVE'),
('D09', 'CBE', 'D09', 'Energy & Building Performance', 'Energy assessment, retrofit, renewables and insulation.', 9, 'ACTIVE'),
('D10', 'CBE', 'D10', 'Facilities, Property & Asset Operations', 'Operational property, assets, planned/reactive maintenance and compliance.', 10, 'ACTIVE'),
('D11', 'CBE', 'D11', 'Plant, Equipment & Specialist Operations', 'Plant, lifting, access, specialist equipment and extraction operations.', 11, 'ACTIVE'),
('D12', 'CBE', 'D12', 'Utilities & Networks', 'Roads, gas and water network field operations.', 12, 'ACTIVE'),
('D13', 'CBE', 'D13', 'Heritage, Conservation & Landscape', 'Heritage, conservation, landscape and specialist craft conservation.', 13, 'ACTIVE'),
('D14', 'CBE', 'D14', 'Supply Chain & Manufacturing', 'Merchants, fabrication/manufacturing, stock and product fulfilment.', 14, 'ACTIVE'),
('D15', 'CBE', 'D15', 'Regulation, Inspection & Compliance', 'Regulatory assessment, inspection, decision and certification workflows.', 15, 'ACTIVE'),
('D16', 'CBE', 'D16', 'Infrastructure, Land & Rural', 'Rural contracting, land operations, mobile resources and field service delivery.', 16, 'ACTIVE');

INSERT INTO job_profiles
  (id, catalogue_scope, tenant_id, code, name, status)
VALUES
('JP-CBE-001', 'PLATFORM', NULL, 'CBE_001', 'Acoustics consultant', 'ACTIVE'),
('JP-CBE-002', 'PLATFORM', NULL, 'CBE_002', 'Agricultural contractor', 'ACTIVE'),
('JP-CBE-003', 'PLATFORM', NULL, 'CBE_003', 'Architect', 'ACTIVE'),
('JP-CBE-004', 'PLATFORM', NULL, 'CBE_004', 'Architectural technician', 'ACTIVE'),
('JP-CBE-005', 'PLATFORM', NULL, 'CBE_005', 'Architectural technologist', 'ACTIVE'),
('JP-CBE-006', 'PLATFORM', NULL, 'CBE_006', 'Bricklayer', 'ACTIVE'),
('JP-CBE-007', 'PLATFORM', NULL, 'CBE_007', 'Builders'' merchant', 'ACTIVE'),
('JP-CBE-008', 'PLATFORM', NULL, 'CBE_008', 'Building control officer', 'ACTIVE'),
('JP-CBE-009', 'PLATFORM', NULL, 'CBE_009', 'Building services engineer', 'ACTIVE'),
('JP-CBE-010', 'PLATFORM', NULL, 'CBE_010', 'Building surveyor', 'ACTIVE'),
('JP-CBE-011', 'PLATFORM', NULL, 'CBE_011', 'Building technician', 'ACTIVE'),
('JP-CBE-012', 'PLATFORM', NULL, 'CBE_012', 'Caretaker', 'ACTIVE'),
('JP-CBE-013', 'PLATFORM', NULL, 'CBE_013', 'Carpenter', 'ACTIVE'),
('JP-CBE-014', 'PLATFORM', NULL, 'CBE_014', 'Carpet fitter and floor layer', 'ACTIVE'),
('JP-CBE-015', 'PLATFORM', NULL, 'CBE_015', 'Cartographer', 'ACTIVE'),
('JP-CBE-016', 'PLATFORM', NULL, 'CBE_016', 'Cavity insulation installer', 'ACTIVE'),
('JP-CBE-017', 'PLATFORM', NULL, 'CBE_017', 'Ceiling fixer', 'ACTIVE'),
('JP-CBE-018', 'PLATFORM', NULL, 'CBE_018', 'Civil engineer', 'ACTIVE'),
('JP-CBE-019', 'PLATFORM', NULL, 'CBE_019', 'Civil engineering technician', 'ACTIVE'),
('JP-CBE-020', 'PLATFORM', NULL, 'CBE_020', 'Commercial energy assessor', 'ACTIVE'),
('JP-CBE-021', 'PLATFORM', NULL, 'CBE_021', 'Conservator', 'ACTIVE'),
('JP-CBE-022', 'PLATFORM', NULL, 'CBE_022', 'Construction contracts manager', 'ACTIVE'),
('JP-CBE-023', 'PLATFORM', NULL, 'CBE_023', 'Construction labourer', 'ACTIVE'),
('JP-CBE-024', 'PLATFORM', NULL, 'CBE_024', 'Construction manager', 'ACTIVE'),
('JP-CBE-025', 'PLATFORM', NULL, 'CBE_025', 'Construction plant mechanic', 'ACTIVE'),
('JP-CBE-026', 'PLATFORM', NULL, 'CBE_026', 'Construction plant operator', 'ACTIVE'),
('JP-CBE-027', 'PLATFORM', NULL, 'CBE_027', 'Construction site supervisor', 'ACTIVE'),
('JP-CBE-028', 'PLATFORM', NULL, 'CBE_028', 'Crane driver', 'ACTIVE'),
('JP-CBE-029', 'PLATFORM', NULL, 'CBE_029', 'Demolition operative', 'ACTIVE'),
('JP-CBE-030', 'PLATFORM', NULL, 'CBE_030', 'Domestic energy assessor', 'ACTIVE'),
('JP-CBE-031', 'PLATFORM', NULL, 'CBE_031', 'Dryliner', 'ACTIVE'),
('JP-CBE-032', 'PLATFORM', NULL, 'CBE_032', 'Electrician', 'ACTIVE'),
('JP-CBE-033', 'PLATFORM', NULL, 'CBE_033', 'Engineering construction technician', 'ACTIVE'),
('JP-CBE-034', 'PLATFORM', NULL, 'CBE_034', 'Estimator', 'ACTIVE'),
('JP-CBE-035', 'PLATFORM', NULL, 'CBE_035', 'Facilities manager', 'ACTIVE'),
('JP-CBE-036', 'PLATFORM', NULL, 'CBE_036', 'Fence installer', 'ACTIVE'),
('JP-CBE-037', 'PLATFORM', NULL, 'CBE_037', 'Fire safety engineer', 'ACTIVE'),
('JP-CBE-038', 'PLATFORM', NULL, 'CBE_038', 'Formworker', 'ACTIVE'),
('JP-CBE-039', 'PLATFORM', NULL, 'CBE_039', 'Furniture maker', 'ACTIVE'),
('JP-CBE-040', 'PLATFORM', NULL, 'CBE_040', 'Gas mains layer', 'ACTIVE'),
('JP-CBE-041', 'PLATFORM', NULL, 'CBE_041', 'Gas service technician', 'ACTIVE'),
('JP-CBE-042', 'PLATFORM', NULL, 'CBE_042', 'General practice surveyor', 'ACTIVE'),
('JP-CBE-043', 'PLATFORM', NULL, 'CBE_043', 'Geospatial technician', 'ACTIVE'),
('JP-CBE-044', 'PLATFORM', NULL, 'CBE_044', 'Glazier', 'ACTIVE'),
('JP-CBE-045', 'PLATFORM', NULL, 'CBE_045', 'Heat pump engineer', 'ACTIVE'),
('JP-CBE-046', 'PLATFORM', NULL, 'CBE_046', 'Heating and ventilation engineer', 'ACTIVE'),
('JP-CBE-047', 'PLATFORM', NULL, 'CBE_047', 'Heritage officer', 'ACTIVE'),
('JP-CBE-048', 'PLATFORM', NULL, 'CBE_048', 'Kitchen and bathroom designer', 'ACTIVE'),
('JP-CBE-049', 'PLATFORM', NULL, 'CBE_049', 'Kitchen and bathroom fitter', 'ACTIVE'),
('JP-CBE-050', 'PLATFORM', NULL, 'CBE_050', 'Land surveyor', 'ACTIVE'),
('JP-CBE-051', 'PLATFORM', NULL, 'CBE_051', 'Landscape architect', 'ACTIVE'),
('JP-CBE-052', 'PLATFORM', NULL, 'CBE_052', 'Landscaper', 'ACTIVE'),
('JP-CBE-053', 'PLATFORM', NULL, 'CBE_053', 'Lighting technician', 'ACTIVE'),
('JP-CBE-054', 'PLATFORM', NULL, 'CBE_054', 'Locksmith', 'ACTIVE'),
('JP-CBE-055', 'PLATFORM', NULL, 'CBE_055', 'Painter and decorator', 'ACTIVE'),
('JP-CBE-056', 'PLATFORM', NULL, 'CBE_056', 'Pipe fitter', 'ACTIVE'),
('JP-CBE-057', 'PLATFORM', NULL, 'CBE_057', 'Planning and development surveyor', 'ACTIVE'),
('JP-CBE-058', 'PLATFORM', NULL, 'CBE_058', 'Plasterer', 'ACTIVE'),
('JP-CBE-059', 'PLATFORM', NULL, 'CBE_059', 'Plumber', 'ACTIVE'),
('JP-CBE-060', 'PLATFORM', NULL, 'CBE_060', 'Quantity surveyor', 'ACTIVE'),
('JP-CBE-061', 'PLATFORM', NULL, 'CBE_061', 'Quarry engineer', 'ACTIVE'),
('JP-CBE-062', 'PLATFORM', NULL, 'CBE_062', 'Quarry worker', 'ACTIVE'),
('JP-CBE-063', 'PLATFORM', NULL, 'CBE_063', 'Refrigeration and air-conditioning installer', 'ACTIVE'),
('JP-CBE-064', 'PLATFORM', NULL, 'CBE_064', 'Road worker', 'ACTIVE'),
('JP-CBE-065', 'PLATFORM', NULL, 'CBE_065', 'Roofer', 'ACTIVE'),
('JP-CBE-066', 'PLATFORM', NULL, 'CBE_066', 'Rural surveyor', 'ACTIVE'),
('JP-CBE-067', 'PLATFORM', NULL, 'CBE_067', 'Scaffolder', 'ACTIVE'),
('JP-CBE-068', 'PLATFORM', NULL, 'CBE_068', 'Security systems installer', 'ACTIVE'),
('JP-CBE-069', 'PLATFORM', NULL, 'CBE_069', 'Shopfitter', 'ACTIVE'),
('JP-CBE-070', 'PLATFORM', NULL, 'CBE_070', 'Solar panel installer', 'ACTIVE'),
('JP-CBE-071', 'PLATFORM', NULL, 'CBE_071', 'Steel erector', 'ACTIVE'),
('JP-CBE-072', 'PLATFORM', NULL, 'CBE_072', 'Steel fixer', 'ACTIVE'),
('JP-CBE-073', 'PLATFORM', NULL, 'CBE_073', 'Steeplejack', 'ACTIVE'),
('JP-CBE-074', 'PLATFORM', NULL, 'CBE_074', 'Stonemason', 'ACTIVE'),
('JP-CBE-075', 'PLATFORM', NULL, 'CBE_075', 'Structural engineer', 'ACTIVE'),
('JP-CBE-076', 'PLATFORM', NULL, 'CBE_076', 'Surveying technician', 'ACTIVE'),
('JP-CBE-077', 'PLATFORM', NULL, 'CBE_077', 'Thermal insulation engineer', 'ACTIVE'),
('JP-CBE-078', 'PLATFORM', NULL, 'CBE_078', 'Tiler', 'ACTIVE'),
('JP-CBE-079', 'PLATFORM', NULL, 'CBE_079', 'Town planner', 'ACTIVE'),
('JP-CBE-080', 'PLATFORM', NULL, 'CBE_080', 'Town planning assistant', 'ACTIVE'),
('JP-CBE-081', 'PLATFORM', NULL, 'CBE_081', 'Transport planner', 'ACTIVE'),
('JP-CBE-082', 'PLATFORM', NULL, 'CBE_082', 'Water network operative', 'ACTIVE'),
('JP-CBE-083', 'PLATFORM', NULL, 'CBE_083', 'Welder', 'ACTIVE'),
('JP-CBE-084', 'PLATFORM', NULL, 'CBE_084', 'Wood machinist', 'ACTIVE');

INSERT INTO industry_job_profiles
  (id, industry_solution_id, job_profile_id, primary_delivery_domain_id,
   sequence, canonical_name, source_name, source_verified_date, status)
VALUES
('CBE-JP-001', 'CBE', 'JP-CBE-001', 'D02', 1, 'Acoustics consultant', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-002', 'CBE', 'JP-CBE-002', 'D16', 2, 'Agricultural contractor', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-003', 'CBE', 'JP-CBE-003', 'D01', 3, 'Architect', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-004', 'CBE', 'JP-CBE-004', 'D01', 4, 'Architectural technician', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-005', 'CBE', 'JP-CBE-005', 'D01', 5, 'Architectural technologist', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-006', 'CBE', 'JP-CBE-006', 'D07', 6, 'Bricklayer', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-007', 'CBE', 'JP-CBE-007', 'D14', 7, 'Builders'' merchant', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-008', 'CBE', 'JP-CBE-008', 'D15', 8, 'Building control officer', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-009', 'CBE', 'JP-CBE-009', 'D02', 9, 'Building services engineer', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-010', 'CBE', 'JP-CBE-010', 'D03', 10, 'Building surveyor', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-011', 'CBE', 'JP-CBE-011', 'D02', 11, 'Building technician', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-012', 'CBE', 'JP-CBE-012', 'D10', 12, 'Caretaker', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-013', 'CBE', 'JP-CBE-013', 'D07', 13, 'Carpenter', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-014', 'CBE', 'JP-CBE-014', 'D07', 14, 'Carpet fitter and floor layer', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-015', 'CBE', 'JP-CBE-015', 'D05', 15, 'Cartographer', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-016', 'CBE', 'JP-CBE-016', 'D09', 16, 'Cavity insulation installer', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-017', 'CBE', 'JP-CBE-017', 'D07', 17, 'Ceiling fixer', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-018', 'CBE', 'JP-CBE-018', 'D02', 18, 'Civil engineer', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-019', 'CBE', 'JP-CBE-019', 'D02', 19, 'Civil engineering technician', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-020', 'CBE', 'JP-CBE-020', 'D09', 20, 'Commercial energy assessor', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-021', 'CBE', 'JP-CBE-021', 'D13', 21, 'Conservator', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-022', 'CBE', 'JP-CBE-022', 'D04', 22, 'Construction contracts manager', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-023', 'CBE', 'JP-CBE-023', 'D06', 23, 'Construction labourer', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-024', 'CBE', 'JP-CBE-024', 'D06', 24, 'Construction manager', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-025', 'CBE', 'JP-CBE-025', 'D11', 25, 'Construction plant mechanic', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-026', 'CBE', 'JP-CBE-026', 'D11', 26, 'Construction plant operator', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-027', 'CBE', 'JP-CBE-027', 'D06', 27, 'Construction site supervisor', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-028', 'CBE', 'JP-CBE-028', 'D11', 28, 'Crane driver', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-029', 'CBE', 'JP-CBE-029', 'D06', 29, 'Demolition operative', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-030', 'CBE', 'JP-CBE-030', 'D09', 30, 'Domestic energy assessor', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-031', 'CBE', 'JP-CBE-031', 'D07', 31, 'Dryliner', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-032', 'CBE', 'JP-CBE-032', 'D08', 32, 'Electrician', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-033', 'CBE', 'JP-CBE-033', 'D02', 33, 'Engineering construction technician', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-034', 'CBE', 'JP-CBE-034', 'D04', 34, 'Estimator', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-035', 'CBE', 'JP-CBE-035', 'D10', 35, 'Facilities manager', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-036', 'CBE', 'JP-CBE-036', 'D07', 36, 'Fence installer', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-037', 'CBE', 'JP-CBE-037', 'D02', 37, 'Fire safety engineer', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-038', 'CBE', 'JP-CBE-038', 'D07', 38, 'Formworker', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-039', 'CBE', 'JP-CBE-039', 'D14', 39, 'Furniture maker', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-040', 'CBE', 'JP-CBE-040', 'D12', 40, 'Gas mains layer', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-041', 'CBE', 'JP-CBE-041', 'D08', 41, 'Gas service technician', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-042', 'CBE', 'JP-CBE-042', 'D03', 42, 'General practice surveyor', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-043', 'CBE', 'JP-CBE-043', 'D05', 43, 'Geospatial technician', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-044', 'CBE', 'JP-CBE-044', 'D07', 44, 'Glazier', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-045', 'CBE', 'JP-CBE-045', 'D08', 45, 'Heat pump engineer', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-046', 'CBE', 'JP-CBE-046', 'D08', 46, 'Heating and ventilation engineer', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-047', 'CBE', 'JP-CBE-047', 'D13', 47, 'Heritage officer', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-048', 'CBE', 'JP-CBE-048', 'D01', 48, 'Kitchen and bathroom designer', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-049', 'CBE', 'JP-CBE-049', 'D07', 49, 'Kitchen and bathroom fitter', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-050', 'CBE', 'JP-CBE-050', 'D03', 50, 'Land surveyor', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-051', 'CBE', 'JP-CBE-051', 'D13', 51, 'Landscape architect', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-052', 'CBE', 'JP-CBE-052', 'D13', 52, 'Landscaper', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-053', 'CBE', 'JP-CBE-053', 'D11', 53, 'Lighting technician', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-054', 'CBE', 'JP-CBE-054', 'D08', 54, 'Locksmith', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-055', 'CBE', 'JP-CBE-055', 'D07', 55, 'Painter and decorator', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-056', 'CBE', 'JP-CBE-056', 'D08', 56, 'Pipe fitter', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-057', 'CBE', 'JP-CBE-057', 'D03', 57, 'Planning and development surveyor', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-058', 'CBE', 'JP-CBE-058', 'D07', 58, 'Plasterer', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-059', 'CBE', 'JP-CBE-059', 'D08', 59, 'Plumber', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-060', 'CBE', 'JP-CBE-060', 'D04', 60, 'Quantity surveyor', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-061', 'CBE', 'JP-CBE-061', 'D11', 61, 'Quarry engineer', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-062', 'CBE', 'JP-CBE-062', 'D11', 62, 'Quarry worker', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-063', 'CBE', 'JP-CBE-063', 'D08', 63, 'Refrigeration and air-conditioning installer', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-064', 'CBE', 'JP-CBE-064', 'D12', 64, 'Road worker', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-065', 'CBE', 'JP-CBE-065', 'D07', 65, 'Roofer', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-066', 'CBE', 'JP-CBE-066', 'D03', 66, 'Rural surveyor', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-067', 'CBE', 'JP-CBE-067', 'D11', 67, 'Scaffolder', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-068', 'CBE', 'JP-CBE-068', 'D08', 68, 'Security systems installer', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-069', 'CBE', 'JP-CBE-069', 'D07', 69, 'Shopfitter', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-070', 'CBE', 'JP-CBE-070', 'D09', 70, 'Solar panel installer', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-071', 'CBE', 'JP-CBE-071', 'D07', 71, 'Steel erector', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-072', 'CBE', 'JP-CBE-072', 'D07', 72, 'Steel fixer', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-073', 'CBE', 'JP-CBE-073', 'D11', 73, 'Steeplejack', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-074', 'CBE', 'JP-CBE-074', 'D13', 74, 'Stonemason', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-075', 'CBE', 'JP-CBE-075', 'D02', 75, 'Structural engineer', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-076', 'CBE', 'JP-CBE-076', 'D03', 76, 'Surveying technician', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-077', 'CBE', 'JP-CBE-077', 'D09', 77, 'Thermal insulation engineer', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-078', 'CBE', 'JP-CBE-078', 'D07', 78, 'Tiler', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-079', 'CBE', 'JP-CBE-079', 'D05', 79, 'Town planner', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-080', 'CBE', 'JP-CBE-080', 'D05', 80, 'Town planning assistant', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-081', 'CBE', 'JP-CBE-081', 'D05', 81, 'Transport planner', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-082', 'CBE', 'JP-CBE-082', 'D12', 82, 'Water network operative', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-083', 'CBE', 'JP-CBE-083', 'D14', 83, 'Welder', 'National Careers Service', '2026-08-15', 'ACTIVE'),
('CBE-JP-084', 'CBE', 'JP-CBE-084', 'D14', 84, 'Wood machinist', 'National Careers Service', '2026-08-15', 'ACTIVE');

INSERT INTO construction_work_product_types
  (id, industry_solution_id, code, name, category, default_authoring_mode,
   governed_output_type, default_representation_types, status)
VALUES
('CBE-WP-DRAWING', 'CBE', 'DRAWING', 'Drawing', 'DESIGN_TECHNICAL', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-MODEL', 'CBE', 'MODEL', 'Model', 'DESIGN_TECHNICAL', 'NATIVE', 'INFORMATION_CONTAINER', '["NATIVE","IFC"]', 'ACTIVE'),
('CBE-WP-CALCULATION', 'CBE', 'CALCULATION', 'Calculation', 'DESIGN_TECHNICAL', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-SPECIFICATION', 'CBE', 'SPECIFICATION', 'Specification', 'DESIGN_TECHNICAL', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-SCHEDULE', 'CBE', 'SCHEDULE', 'Schedule', 'DESIGN_TECHNICAL', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-DESIGN_DECISION', 'CBE', 'DESIGN_DECISION', 'Design Decision', 'DESIGN_TECHNICAL', 'NATIVE', 'DECISION', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-SURVEY', 'CBE', 'SURVEY', 'Survey', 'DESIGN_TECHNICAL', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-TECHNICAL_SUBMISSION', 'CBE', 'TECHNICAL_SUBMISSION', 'Technical Submission', 'DESIGN_TECHNICAL', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-RFI_RESPONSE', 'CBE', 'RFI_RESPONSE', 'RFI Response', 'DESIGN_TECHNICAL', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-DESIGN_REVIEW_RECORD', 'CBE', 'DESIGN_REVIEW_RECORD', 'Design Review Record', 'DESIGN_TECHNICAL', 'NATIVE', 'EVIDENCE_RECORD', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-ESTIMATE', 'CBE', 'ESTIMATE', 'Estimate', 'COMMERCIAL_CONTRACTUAL', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-COST_PLAN', 'CBE', 'COST_PLAN', 'Cost Plan', 'COMMERCIAL_CONTRACTUAL', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-BOQ', 'CBE', 'BOQ', 'Bill of Quantities', 'COMMERCIAL_CONTRACTUAL', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-TENDER_RETURN', 'CBE', 'TENDER_RETURN', 'Tender Return', 'COMMERCIAL_CONTRACTUAL', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-CONTRACT', 'CBE', 'CONTRACT', 'Contract', 'COMMERCIAL_CONTRACTUAL', 'NATIVE', 'CONTRACT', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-INSTRUCTION', 'CBE', 'INSTRUCTION', 'Instruction', 'COMMERCIAL_CONTRACTUAL', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-VARIATION', 'CBE', 'VARIATION', 'Variation', 'COMMERCIAL_CONTRACTUAL', 'NATIVE', 'CHANGE', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-VALUATION', 'CBE', 'VALUATION', 'Valuation', 'COMMERCIAL_CONTRACTUAL', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-PAYMENT_CERTIFICATE', 'CBE', 'PAYMENT_CERTIFICATE', 'Payment Certificate', 'COMMERCIAL_CONTRACTUAL', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-FINAL_ACCOUNT', 'CBE', 'FINAL_ACCOUNT', 'Final Account', 'COMMERCIAL_CONTRACTUAL', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-REQUISITION', 'CBE', 'REQUISITION', 'Requisition', 'PROCUREMENT_SUPPLY', 'NATIVE', 'INFORMATION_CONTAINER', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-RFQ', 'CBE', 'RFQ', 'Request for Quotation', 'PROCUREMENT_SUPPLY', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-PURCHASE_ORDER', 'CBE', 'PURCHASE_ORDER', 'Purchase Order', 'PROCUREMENT_SUPPLY', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-MATERIAL_SUBMITTAL', 'CBE', 'MATERIAL_SUBMITTAL', 'Material Submittal', 'PROCUREMENT_SUPPLY', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-DELIVERY_RECORD', 'CBE', 'DELIVERY_RECORD', 'Delivery Record', 'PROCUREMENT_SUPPLY', 'NATIVE', 'EVIDENCE_RECORD', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-GOODS_RECEIPT', 'CBE', 'GOODS_RECEIPT', 'Goods Receipt', 'PROCUREMENT_SUPPLY', 'NATIVE', 'EVIDENCE_RECORD', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-MATERIAL_TRACEABILITY_RECORD', 'CBE', 'MATERIAL_TRACEABILITY_RECORD', 'Material Traceability Record', 'PROCUREMENT_SUPPLY', 'NATIVE', 'EVIDENCE_RECORD', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-BOM', 'CBE', 'BOM', 'Bill of Materials', 'PRODUCTION_FABRICATION', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-FABRICATION_DRAWING', 'CBE', 'FABRICATION_DRAWING', 'Fabrication Drawing', 'PRODUCTION_FABRICATION', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-CUT_LIST', 'CBE', 'CUT_LIST', 'Cut List', 'PRODUCTION_FABRICATION', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-PRODUCTION_ORDER', 'CBE', 'PRODUCTION_ORDER', 'Production Order', 'PRODUCTION_FABRICATION', 'NATIVE', 'PRODUCTION_ORDER', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-WELD_RECORD', 'CBE', 'WELD_RECORD', 'Weld Record', 'PRODUCTION_FABRICATION', 'NATIVE', 'EVIDENCE_RECORD', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-MANUFACTURED_COMPONENT', 'CBE', 'MANUFACTURED_COMPONENT', 'Manufactured Component', 'PRODUCTION_FABRICATION', 'NATIVE', 'ASSET', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-WORK_PACKAGE', 'CBE', 'WORK_PACKAGE', 'Work Package', 'SITE_DELIVERY', 'NATIVE', 'WORK_PACKAGE', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-CONTROLLED_WORK_INFORMATION', 'CBE', 'CONTROLLED_WORK_INFORMATION', 'Controlled Work Information / Method', 'SITE_DELIVERY', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-INSTALLED_WORK', 'CBE', 'INSTALLED_WORK', 'Installed Work', 'SITE_DELIVERY', 'NATIVE', 'ASSET', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-PROGRESS_EVIDENCE', 'CBE', 'PROGRESS_EVIDENCE', 'Progress Evidence', 'SITE_DELIVERY', 'NATIVE', 'EVIDENCE_RECORD', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-PERMIT', 'CBE', 'PERMIT', 'Permit', 'SITE_DELIVERY', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-INSPECTION', 'CBE', 'INSPECTION', 'Inspection', 'SITE_DELIVERY', 'NATIVE', 'EVIDENCE_RECORD', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-TEST', 'CBE', 'TEST', 'Test', 'SITE_DELIVERY', 'NATIVE', 'EVIDENCE_RECORD', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-NON_CONFORMANCE', 'CBE', 'NON_CONFORMANCE', 'Non-conformance', 'SITE_DELIVERY', 'NATIVE', 'CHANGE', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-CORRECTIVE_ACTION', 'CBE', 'CORRECTIVE_ACTION', 'Corrective Action', 'SITE_DELIVERY', 'NATIVE', 'WORK_ITEM', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-COMMISSIONING_PLAN', 'CBE', 'COMMISSIONING_PLAN', 'Commissioning Plan', 'COMMISSIONING_HANDOVER', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-TEST_RESULT', 'CBE', 'TEST_RESULT', 'Test Result', 'COMMISSIONING_HANDOVER', 'NATIVE', 'EVIDENCE_RECORD', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-COMMISSIONING_RECORD', 'CBE', 'COMMISSIONING_RECORD', 'Commissioning Record', 'COMMISSIONING_HANDOVER', 'NATIVE', 'EVIDENCE_RECORD', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-OM_INFORMATION', 'CBE', 'OM_INFORMATION', 'O&M Information', 'COMMISSIONING_HANDOVER', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-TRAINING_RECORD', 'CBE', 'TRAINING_RECORD', 'Training Record', 'COMMISSIONING_HANDOVER', 'NATIVE', 'EVIDENCE_RECORD', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-AS_BUILT_INFORMATION', 'CBE', 'AS_BUILT_INFORMATION', 'As-built Information', 'COMMISSIONING_HANDOVER', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-ASSET_INFORMATION', 'CBE', 'ASSET_INFORMATION', 'Asset Information', 'COMMISSIONING_HANDOVER', 'NATIVE', 'INFORMATION_CONTAINER', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-HANDOVER_CERTIFICATE', 'CBE', 'HANDOVER_CERTIFICATE', 'Handover Certificate', 'COMMISSIONING_HANDOVER', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE'),
('CBE-WP-ASSET_RECORD', 'CBE', 'ASSET_RECORD', 'Asset Record', 'OPERATIONS_MAINTENANCE', 'NATIVE', 'ASSET', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-WORK_ORDER', 'CBE', 'WORK_ORDER', 'Work Order', 'OPERATIONS_MAINTENANCE', 'NATIVE', 'WORK_ITEM', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-DEFECT', 'CBE', 'DEFECT', 'Defect', 'OPERATIONS_MAINTENANCE', 'NATIVE', 'CHANGE', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-CONDITION_ASSESSMENT', 'CBE', 'CONDITION_ASSESSMENT', 'Condition Assessment', 'OPERATIONS_MAINTENANCE', 'NATIVE', 'EVIDENCE_RECORD', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-MAINTENANCE_INSPECTION', 'CBE', 'MAINTENANCE_INSPECTION', 'Maintenance Inspection', 'OPERATIONS_MAINTENANCE', 'NATIVE', 'EVIDENCE_RECORD', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-MAINTENANCE_HISTORY', 'CBE', 'MAINTENANCE_HISTORY', 'Maintenance History', 'OPERATIONS_MAINTENANCE', 'NATIVE', 'EVIDENCE_RECORD', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-COMPLIANCE_EVIDENCE', 'CBE', 'COMPLIANCE_EVIDENCE', 'Statutory / Compliance Evidence', 'OPERATIONS_MAINTENANCE', 'NATIVE', 'EVIDENCE_RECORD', '["NATIVE"]', 'ACTIVE'),
('CBE-WP-SERVICE_REPORT', 'CBE', 'SERVICE_REPORT', 'Service Report', 'OPERATIONS_MAINTENANCE', 'NATIVE', 'INFORMATION_CONTAINER', '["PDF","NATIVE"]', 'ACTIVE');
