CREATE TABLE industry_job_capability_profiles (
  industry_job_profile_id VARCHAR(64) NOT NULL PRIMARY KEY,
  specialist_capabilities JSON NOT NULL,
  primary_structured_records JSON NOT NULL,
  lifecycle_stages JSON NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_industry_job_capability_profiles_job
    FOREIGN KEY (industry_job_profile_id)
    REFERENCES industry_job_profiles(id)
) ENGINE=InnoDB;

INSERT INTO industry_job_capability_profiles
  (industry_job_profile_id, specialist_capabilities,
   primary_structured_records, lifecycle_stages)
VALUES
('CBE-JP-001', '["Acoustic surveys","noise and vibration assessment","modelling","design recommendations","compliance evidence"]', '["Survey reports","models","recommendations","specifications"]', '["Feasibility","Design","Verification"]'),
('CBE-JP-002', '["Job planning","field operations","plant allocation","labour","materials","service records"]', '["Work orders","field logs","plant records","invoices"]', '["Planning","Delivery","Maintenance"]'),
('CBE-JP-003', '["Briefing","design stages","drawings","specifications","coordination","planning","approvals","site reviews"]', '["Drawings","models","specifications","design decisions","inspection records"]', '["Brief","Design","Construction","Handover"]'),
('CBE-JP-004', '["Technical drawings","detailing","schedules","coordination","document production"]', '["Drawings","details","schedules","issue sheets"]', '["Design","Construction"]'),
('CBE-JP-005', '["Technical design management","detailing","compliance","specifications","coordination"]', '["Technical designs","specifications","schedules","compliance records"]', '["Design","Construction","Handover"]'),
('CBE-JP-006', '["Job planning","setting out","masonry works","materials","progress","quality checks"]', '["Work orders","material usage","photos","quality records"]', '["Construction"]'),
('CBE-JP-007', '["Catalogue","stock","quotations","orders","trade accounts","deliveries","returns"]', '["Products","stock","quotes","sales orders","delivery notes","invoices"]', '["Procurement","Supply"]'),
('CBE-JP-008', '["Applications","plan assessment","inspections","evidence","defects","decisions"]', '["Applications","inspection records","notices","decisions","certificates"]', '["Design","Construction","Completion"]'),
('CBE-JP-009', '["MEP design","calculations","equipment schedules","coordination","commissioning requirements"]', '["Designs","calculations","specifications","equipment schedules"]', '["Design","Construction","Commissioning"]'),
('CBE-JP-010', '["Condition surveys","defects","schedules","project advice","dilapidations","maintenance planning"]', '["Survey reports","defect schedules","photos","scopes","certificates"]', '["Survey","Design","Construction","Operations"]'),
('CBE-JP-011', '["Technical support","drawings","surveys","records","project coordination"]', '["Drawings","survey data","schedules","reports"]', '["Design","Construction"]'),
('CBE-JP-012', '["Inspections","reactive tasks","access","cleaning/maintenance coordination","incident reporting"]', '["Work orders","checks","logs","incident records"]', '["Operations"]'),
('CBE-JP-013', '["Job planning","setting out","fabrication","installation","materials","quality"]', '["Work orders","cut lists","material usage","photos"]', '["Construction"]'),
('CBE-JP-014', '["Site measure","product selection","preparation","installation","snagging"]', '["Measurements","material schedules","work orders","completion records"]', '["Fit-out"]'),
('CBE-JP-015', '["Spatial data management","map production","revisions","exports"]', '["Maps","datasets","layers","metadata"]', '["Survey","Planning","Design"]'),
('CBE-JP-016', '["Survey","suitability checks","installation","materials","photos","completion evidence"]', '["Survey records","installation records","certificates","photos"]', '["Retrofit","Completion"]'),
('CBE-JP-017', '["Take-off","layout","installation","materials","progress","snagging"]', '["Work orders","material usage","photos","defects"]', '["Fit-out"]'),
('CBE-JP-018', '["Civil design","calculations","specifications","coordination","site queries","inspections"]', '["Designs","calculations","specifications","RFIs","inspection records"]', '["Feasibility","Design","Construction"]'),
('CBE-JP-019', '["CAD/BIM support","surveys","calculations","drawings","records"]', '["Drawings","models","survey data","schedules"]', '["Design","Construction"]'),
('CBE-JP-020', '["Property data capture","energy assessment","evidence","certificate workflow"]', '["Assessment records","evidence","EPC-related outputs"]', '["Survey","Assessment","Certification"]'),
('CBE-JP-021', '["Condition assessment","conservation plan","treatment records","provenance/evidence"]', '["Condition reports","treatment plans","photos","conservation records"]', '["Survey","Conservation","Maintenance"]'),
('CBE-JP-022', '["Contract register","obligations","notices","change","payment","claims","correspondence"]', '["Contracts","notices","instructions","variations","payment records"]', '["Pre-contract","Construction","Closeout"]'),
('CBE-JP-023', '["Task allocation","attendance","inductions","daily work","equipment","safety records"]', '["Timesheets","task records","inductions","site diary entries"]', '["Construction"]'),
('CBE-JP-024', '["Programme","packages","coordination","site diary","labour","plant","quality","safety","progress"]', '["Programme","diaries","RFIs","reports","inspections","progress records"]', '["Pre-construction","Construction","Handover"]'),
('CBE-JP-025', '["Asset register","servicing","defects","inspections","parts","breakdowns"]', '["Asset records","service history","defect reports","work orders"]', '["Construction","Maintenance"]'),
('CBE-JP-026', '["Plant allocation","pre-use checks","hours","tasks","defects","competencies"]', '["Plant checks","utilisation","task logs","defect records"]', '["Construction"]'),
('CBE-JP-027', '["Daily supervision","labour","inspections","permits","quality","progress","safety"]', '["Site diary","inspections","permits","progress records"]', '["Construction"]'),
('CBE-JP-028', '["Lift allocation","pre-use checks","plant hours","competency","lift records","defects"]', '["Checks","lift logs","utilisation","defect records"]', '["Construction"]'),
('CBE-JP-029', '["Method/task planning","permits","hazardous materials records","waste","progress"]', '["RAMS references","permits","waste records","photos","task logs"]', '["Enabling","Demolition"]'),
('CBE-JP-030', '["Dwelling data capture","energy assessment","evidence","certificate workflow"]', '["Assessment records","evidence","EPC-related outputs"]', '["Survey","Assessment","Certification"]'),
('CBE-JP-031', '["Take-off","layout","installation","materials","progress","defects"]', '["Work orders","material usage","photos","snagging"]', '["Fit-out"]'),
('CBE-JP-032', '["Survey","estimate","schedule","installation","circuits","testing","defects","certification","maintenance"]', '["Quotes","job sheets","circuit/test records","certificates","invoices"]', '["Design support","Installation","Testing","Maintenance"]'),
('CBE-JP-033', '["Technical support","installation records","commissioning/decommissioning support","drawings"]', '["Drawings","technical records","test sheets","schedules"]', '["Design","Installation","Commissioning"]'),
('CBE-JP-034', '["Take-off","resource build-ups","supplier enquiries","estimates","tender submissions","revisions"]', '["Estimates","take-offs","RFQs","tender returns","bid documents"]', '["Pre-contract"]'),
('CBE-JP-035', '["Property/asset register","PPM","reactive maintenance","compliance","contractors","SLAs","budgets"]', '["Assets","work orders","service records","inspections","compliance evidence"]', '["Operations"]'),
('CBE-JP-036', '["Survey","estimate","set-out","installation","materials","completion"]', '["Quotes","work orders","material usage","photos"]', '["Construction / External works"]'),
('CBE-JP-037', '["Fire strategy","modelling","design review","compliance evidence","inspections"]', '["Fire strategies","calculations","reports","design comments"]', '["Design","Construction","Operations"]'),
('CBE-JP-038', '["Formwork planning","drawings","material/plant requirements","installation","striking","checks"]', '["Work orders","checklists","material records","photos"]', '["Structural construction"]'),
('CBE-JP-039', '["Design","BOM","production","stock","quality","orders","delivery"]', '["Drawings","BOMs","work orders","QC records","sales orders"]', '["Manufacture","Supply"]'),
('CBE-JP-040', '["Work orders","excavation/laying records","materials","pressure/test records","reinstatement","asset location"]', '["Job packs","network records","test results","as-builts"]', '["Infrastructure construction","Maintenance"]'),
('CBE-JP-041', '["Jobs","appliances","service schedules","tests","defects","parts","certification"]', '["Job sheets","appliance records","test results","service records"]', '["Installation","Maintenance"]'),
('CBE-JP-042', '["Property records","valuations","transactions","leases","development appraisal","client advice"]', '["Valuations","property records","instructions","reports"]', '["Acquisition","Development","Operations"]'),
('CBE-JP-043', '["Data capture","GIS layers","coordinate/reference management","mapping","exports"]', '["Spatial datasets","maps","metadata"]', '["Survey","Planning","Construction"]'),
('CBE-JP-044', '["Measure","quote","product/order","installation","repair","completion"]', '["Measurements","quotes","work orders","product records","photos"]', '["Fit-out","Maintenance"]'),
('CBE-JP-045', '["Survey","sizing","estimate","installation","commissioning","servicing","evidence"]', '["Survey","calculations","job sheets","commissioning/test records"]', '["Retrofit/Installation","Maintenance"]'),
('CBE-JP-046', '["Survey","design support","installation","commissioning","service","defects"]', '["Job sheets","equipment records","test/commissioning sheets"]', '["Installation","Commissioning","Maintenance"]'),
('CBE-JP-047', '["Heritage asset records","significance assessment","consultations","case management","condition monitoring"]', '["Case files","assessments","consultation records","reports"]', '["Planning","Conservation","Operations"]'),
('CBE-JP-048', '["Customer brief","survey","layouts","products","quotation","revisions","approvals"]', '["Layouts","product schedules","quotes","approvals"]', '["Sales","Design","Fit-out"]'),
('CBE-JP-049', '["Survey","schedule","installation tasks","materials","coordination","snagging"]', '["Work orders","material lists","photos","completion records"]', '["Fit-out"]'),
('CBE-JP-050', '["Survey planning","observations","control","coordinates","topographical outputs","setting out"]', '["Survey files","point data","drawings","reports"]', '["Survey","Design","Construction"]'),
('CBE-JP-051', '["Brief","site analysis","landscape design","specifications","planting","coordination","inspections"]', '["Plans","schedules","specifications","inspection records"]', '["Planning","Design","Construction"]'),
('CBE-JP-052', '["Quotes","site works","planting/materials","labour","maintenance schedule"]', '["Work orders","material schedules","photos","maintenance records"]', '["External works","Maintenance"]'),
('CBE-JP-053', '["Equipment planning","inventory","setup","inspections","operation","maintenance"]', '["Equipment lists","checklists","allocation records","faults"]', '["Installation/Event delivery","Maintenance"]'),
('CBE-JP-054', '["Callouts","asset/lock register","access hardware","installation","repair","key/control records"]', '["Jobs","asset records","key/access records","invoices"]', '["Installation","Maintenance"]'),
('CBE-JP-055', '["Estimate","area/take-off","materials","schedule","application","completion"]', '["Quotes","work orders","material usage","photos"]', '["Finishes"]'),
('CBE-JP-056', '["Isometrics/work packs","fabrication/installation","weld/test references","materials","QA"]', '["Work packs","spool/line records","test records","material traceability"]', '["Installation","Testing"]'),
('CBE-JP-057', '["Site appraisal","development appraisal","planning constraints","valuations","viability","client reports"]', '["Appraisals","reports","valuations","planning records"]', '["Feasibility","Planning"]'),
('CBE-JP-058', '["Estimate","areas","materials","schedule","application","snagging"]', '["Quotes","work orders","material usage","photos"]', '["Finishes"]'),
('CBE-JP-059', '["Survey","quote","schedule","installation","fixtures","testing","callouts","maintenance"]', '["Quotes","job sheets","test records","asset/service records","invoices"]', '["Installation","Testing","Maintenance"]'),
('CBE-JP-060', '["Measurement","cost plans","procurement","tender analysis","valuations","variations","forecasts","final accounts"]', '["Cost plans","BoQs","tender analyses","valuations","variations","cost reports"]', '["Feasibility","Design","Construction","Final account"]'),
('CBE-JP-061', '["Site/production planning","extraction records","plant","safety","environmental/restoration records"]', '["Plans","production records","inspections","environmental records"]', '["Extraction","Restoration"]'),
('CBE-JP-062', '["Tasks","plant checks","production logs","materials","safety","maintenance defects"]', '["Shift logs","plant checks","production records"]', '["Extraction"]'),
('CBE-JP-063', '["Survey","equipment selection","installation","commissioning","refrigerant/service records","maintenance"]', '["Job sheets","equipment records","commissioning/test records","service logs"]', '["Installation","Commissioning","Maintenance"]'),
('CBE-JP-064', '["Work packs","traffic-management references","plant","materials","daily progress","inspections"]', '["Work orders","daily records","material usage","inspection records"]', '["Infrastructure construction","Maintenance"]'),
('CBE-JP-065', '["Survey","estimate","materials","access","installation/repair","inspections","photos"]', '["Quotes","work orders","material schedules","photos"]', '["Envelope construction","Maintenance"]'),
('CBE-JP-066', '["Land/property records","valuations","tenancy/estate work","land management","inspections"]', '["Valuations","plans","property records","reports"]', '["Acquisition","Management"]'),
('CBE-JP-067', '["Scaffold design/reference","erection","inspection","handover","tagging","alterations","dismantle"]', '["Scaffold register","inspection records","handover certificates"]', '["Construction enabling works"]'),
('CBE-JP-068', '["Survey","quote","device/system design","installation","testing","commissioning","maintenance"]', '["Quotes","device registers","test results","commissioning/service records"]', '["Installation","Commissioning","Maintenance"]'),
('CBE-JP-069', '["Survey","programme","fabrication/install coordination","materials","snagging","handover"]', '["Work orders","drawings","material schedules","snagging records"]', '["Fit-out"]'),
('CBE-JP-070', '["Survey","system sizing/design inputs","quote","installation","testing","commissioning","maintenance"]', '["Survey","quotes","equipment records","commissioning/test records"]', '["Retrofit/Installation","Maintenance"]'),
('CBE-JP-071', '["Work packs","lifts","sequence","members","bolts/connections","inspections","progress"]', '["Work packs","member records","inspection records","photos"]', '["Structural construction"]'),
('CBE-JP-072', '["Bar schedules/reference","work areas","installation","checks","progress"]', '["Work orders","reinforcement records","inspections","photos"]', '["Structural construction"]'),
('CBE-JP-073', '["Access planning","inspection","repair","maintenance","lightning protection records","photos"]', '["Inspection reports","work orders","test records","photos"]', '["Maintenance / Specialist works"]'),
('CBE-JP-074', '["Survey/template","fabrication","installation","conservation repair","material traceability"]', '["Templates","work orders","material records","photos"]', '["Construction","Conservation"]'),
('CBE-JP-075', '["Structural analysis","calculations","drawings","specifications","design changes","inspections"]', '["Calculations","models","drawings","specifications","inspection records"]', '["Design","Construction"]'),
('CBE-JP-076', '["Survey support","site data","measurements","drawings","records","inspections"]', '["Survey data","drawings","schedules","reports"]', '["Survey","Design","Construction"]'),
('CBE-JP-077', '["Take-off","materials","installation","quality checks","completion evidence"]', '["Work orders","material usage","inspection records","photos"]', '["Installation","Completion"]'),
('CBE-JP-078', '["Measure","estimate","layout","materials","installation","snagging"]', '["Quotes","work orders","material usage","photos"]', '["Finishes"]'),
('CBE-JP-079', '["Planning cases","policy/constraints","consultations","site appraisal","reports","decisions tracking"]', '["Applications/cases","consultation records","reports","spatial data"]', '["Feasibility","Planning"]'),
('CBE-JP-080', '["Application processing","data gathering","plans","consultations","case administration"]', '["Case records","plans","consultation records"]', '["Planning"]'),
('CBE-JP-081', '["Demand/network analysis","options","modelling","consultation","reports","programme interfaces"]', '["Models","datasets","option reports","plans"]', '["Feasibility","Planning","Design"]'),
('CBE-JP-082', '["Work orders","network asset location","repairs","leakage","tests","reinstatement","as-builts"]', '["Job packs","network records","test results","as-builts"]', '["Infrastructure construction","Maintenance"]'),
('CBE-JP-083', '["Work packs","weld procedures/references","material traceability","weld logs","inspections","repairs"]', '["Weld logs","material records","inspection/NDT references","work orders"]', '["Fabrication","Construction"]'),
('CBE-JP-084', '["Cut lists","machine jobs","BOM/material stock","quality","production output"]', '["Cut lists","work orders","material records","QC records"]', '["Manufacture"]');
