CREATE TABLE market_capability_catalogues (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  code VARCHAR(80) NOT NULL,
  name VARCHAR(255) NOT NULL,
  edition VARCHAR(64) NOT NULL,
  description TEXT NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_market_capability_catalogue_code_edition (code, edition),
  CONSTRAINT chk_market_capability_catalogue_status CHECK (
    status IN ('ACTIVE', 'INACTIVE')
  )
) ENGINE=InnoDB;

CREATE TABLE market_capability_references (
  id VARCHAR(96) NOT NULL PRIMARY KEY,
  catalogue_id VARCHAR(64) NOT NULL,
  capability_key VARCHAR(80) NOT NULL,
  name VARCHAR(255) NOT NULL,
  capability_group VARCHAR(32) NOT NULL,
  source_detail TEXT NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_market_capability_reference_key (catalogue_id, capability_key),
  CONSTRAINT fk_market_capability_reference_catalogue
    FOREIGN KEY (catalogue_id) REFERENCES market_capability_catalogues(id),
  CONSTRAINT chk_market_capability_reference_group CHECK (
    capability_group IN ('CORE', 'OPERATIONAL_INDUSTRY')
  ),
  CONSTRAINT chk_market_capability_reference_status CHECK (
    status IN ('ACTIVE', 'INACTIVE')
  )
) ENGINE=InnoDB;

CREATE TABLE business_classification_capability_guidance (
  classification_value_id VARCHAR(96) NOT NULL,
  capability_reference_id VARCHAR(96) NOT NULL,
  source_symbol VARCHAR(4) NOT NULL,
  source_state VARCHAR(32) NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (classification_value_id, capability_reference_id),
  KEY ix_business_classification_capability_state
    (classification_value_id, source_state),
  CONSTRAINT fk_business_classification_capability_value
    FOREIGN KEY (classification_value_id) REFERENCES business_classification_values(id),
  CONSTRAINT fk_business_classification_capability_reference
    FOREIGN KEY (capability_reference_id) REFERENCES market_capability_references(id),
  CONSTRAINT chk_business_classification_capability_symbol CHECK (
    source_symbol IN ('●', '○', '—')
  ),
  CONSTRAINT chk_business_classification_capability_state CHECK (
    source_state IN ('DEFAULT_ENABLED', 'AVAILABLE_DISABLED', 'HIDDEN_NOT_APPLICABLE')
  )
) ENGINE=InnoDB;

INSERT INTO market_capability_catalogues
  (id, code, name, edition, description, status)
VALUES
  (
    'MCAT-ERP-MODULES-1',
    'SOURCE_ERP_MODULE_CATALOG',
    'Canonical ERP Module Catalog',
    '1',
    'External ERP capability reference supplied as onboarding and market-requirement evidence. It does not define NuBlox Functions, navigation, permissions or runtime module enablement.',
    'ACTIVE'
  );

INSERT INTO market_capability_references
  (id, catalogue_id, capability_key, name, capability_group, source_detail, status)
VALUES
  ('MCR-ERP-finance', 'MCAT-ERP-MODULES-1', 'finance', 'Financial Management', 'CORE', 'General ledger, AP, AR, fixed assets, bank reconciliation, financial reporting', 'ACTIVE'),
  ('MCR-ERP-hr', 'MCAT-ERP-MODULES-1', 'hr', 'Human Resources', 'CORE', 'Employee records, org structure, absence management, HR compliance', 'ACTIVE'),
  ('MCR-ERP-payroll', 'MCAT-ERP-MODULES-1', 'payroll', 'Payroll', 'CORE', 'Pay runs, tax withholding, statutory deductions, payslips', 'ACTIVE'),
  ('MCR-ERP-crm', 'MCAT-ERP-MODULES-1', 'crm', 'Customer Relationship Management', 'CORE', 'Contacts, leads, opportunities, pipeline, activity tracking', 'ACTIVE'),
  ('MCR-ERP-documents', 'MCAT-ERP-MODULES-1', 'documents', 'Document Management', 'CORE', 'File vaulting, versioning, retention policies, e-signatures', 'ACTIVE'),
  ('MCR-ERP-intranet', 'MCAT-ERP-MODULES-1', 'intranet', 'Intranet & Collaboration', 'CORE', 'Internal pages, announcements, wikis, team spaces, notifications', 'ACTIVE'),
  ('MCR-ERP-admin', 'MCAT-ERP-MODULES-1', 'admin', 'Administration & RBAC', 'CORE', 'User management, roles, permissions, audit logs, tenant settings', 'ACTIVE'),
  ('MCR-ERP-analytics', 'MCAT-ERP-MODULES-1', 'analytics', 'Analytics & Reporting', 'CORE', 'Dashboards, report builder, KPI tracking, data export', 'ACTIVE'),
  ('MCR-ERP-projects', 'MCAT-ERP-MODULES-1', 'projects', 'Project Management', 'OPERATIONAL_INDUSTRY', '23, 54, 55, 56, 61, 71', 'ACTIVE'),
  ('MCR-ERP-job_costing', 'MCAT-ERP-MODULES-1', 'job_costing', 'Job Costing & Project Accounting', 'OPERATIONAL_INDUSTRY', '23, 54, 55', 'ACTIVE'),
  ('MCR-ERP-field_service', 'MCAT-ERP-MODULES-1', 'field_service', 'Field Service Management', 'OPERATIONAL_INDUSTRY', '23, 22, 56, 81', 'ACTIVE'),
  ('MCR-ERP-inventory', 'MCAT-ERP-MODULES-1', 'inventory', 'Inventory Management', 'OPERATIONAL_INDUSTRY', '31–33, 42, 44–45, 81', 'ACTIVE'),
  ('MCR-ERP-procurement', 'MCAT-ERP-MODULES-1', 'procurement', 'Procurement & Purchasing', 'OPERATIONAL_INDUSTRY', '23, 31–33, 42, 44–45, 62, 72', 'ACTIVE'),
  ('MCR-ERP-sales_orders', 'MCAT-ERP-MODULES-1', 'sales_orders', 'Sales Order Management', 'OPERATIONAL_INDUSTRY', '31–33, 42, 44–45, 81', 'ACTIVE'),
  ('MCR-ERP-pos', 'MCAT-ERP-MODULES-1', 'pos', 'Point of Sale', 'OPERATIONAL_INDUSTRY', '44–45, 72', 'ACTIVE'),
  ('MCR-ERP-manufacturing', 'MCAT-ERP-MODULES-1', 'manufacturing', 'Manufacturing (MRP/BOM/Work Orders)', 'OPERATIONAL_INDUSTRY', '31–33', 'ACTIVE'),
  ('MCR-ERP-quality', 'MCAT-ERP-MODULES-1', 'quality', 'Quality Management', 'OPERATIONAL_INDUSTRY', '31–33, 62', 'ACTIVE'),
  ('MCR-ERP-maintenance', 'MCAT-ERP-MODULES-1', 'maintenance', 'Asset Maintenance (CMMS)', 'OPERATIONAL_INDUSTRY', '22, 23, 31–33, 48–49, 53', 'ACTIVE'),
  ('MCR-ERP-fleet', 'MCAT-ERP-MODULES-1', 'fleet', 'Fleet Management', 'OPERATIONAL_INDUSTRY', '48–49, 22, 23, 56', 'ACTIVE'),
  ('MCR-ERP-warehouse', 'MCAT-ERP-MODULES-1', 'warehouse', 'Warehouse Management (WMS)', 'OPERATIONAL_INDUSTRY', '42, 48–49, 31–33', 'ACTIVE'),
  ('MCR-ERP-supply_chain', 'MCAT-ERP-MODULES-1', 'supply_chain', 'Supply Chain Planning', 'OPERATIONAL_INDUSTRY', '31–33, 42, 44–45', 'ACTIVE'),
  ('MCR-ERP-clinical', 'MCAT-ERP-MODULES-1', 'clinical', 'Clinical Records (EMR/EHR)', 'OPERATIONAL_INDUSTRY', '62', 'ACTIVE'),
  ('MCR-ERP-scheduling', 'MCAT-ERP-MODULES-1', 'scheduling', 'Appointment & Resource Scheduling', 'OPERATIONAL_INDUSTRY', '62, 61, 72, 71, 81', 'ACTIVE'),
  ('MCR-ERP-patient_billing', 'MCAT-ERP-MODULES-1', 'patient_billing', 'Patient Billing & Claims', 'OPERATIONAL_INDUSTRY', '62', 'ACTIVE'),
  ('MCR-ERP-compliance', 'MCAT-ERP-MODULES-1', 'compliance', 'Compliance & Regulatory Management', 'OPERATIONAL_INDUSTRY', '52, 62, 21, 22, 31–33', 'ACTIVE'),
  ('MCR-ERP-risk', 'MCAT-ERP-MODULES-1', 'risk', 'Risk Management', 'OPERATIONAL_INDUSTRY', '52, 21, 22, 55', 'ACTIVE'),
  ('MCR-ERP-subscriptions', 'MCAT-ERP-MODULES-1', 'subscriptions', 'Subscription & Recurring Billing', 'OPERATIONAL_INDUSTRY', '51, 54, 55, 61, 71, 81', 'ACTIVE'),
  ('MCR-ERP-time_tracking', 'MCAT-ERP-MODULES-1', 'time_tracking', 'Time & Expense Tracking', 'OPERATIONAL_INDUSTRY', '54, 55, 56, 51, 61, 71', 'ACTIVE'),
  ('MCR-ERP-resource_planning', 'MCAT-ERP-MODULES-1', 'resource_planning', 'Resource Planning & Utilisation', 'OPERATIONAL_INDUSTRY', '54, 55, 56, 51', 'ACTIVE'),
  ('MCR-ERP-ecommerce', 'MCAT-ERP-MODULES-1', 'ecommerce', 'E-commerce Integration', 'OPERATIONAL_INDUSTRY', '44–45, 31–33, 42', 'ACTIVE'),
  ('MCR-ERP-loyalty', 'MCAT-ERP-MODULES-1', 'loyalty', 'Loyalty & Promotions', 'OPERATIONAL_INDUSTRY', '44–45, 72, 71', 'ACTIVE'),
  ('MCR-ERP-reservations', 'MCAT-ERP-MODULES-1', 'reservations', 'Booking & Reservations', 'OPERATIONAL_INDUSTRY', '72, 71, 48–49', 'ACTIVE'),
  ('MCR-ERP-housekeeping', 'MCAT-ERP-MODULES-1', 'housekeeping', 'Housekeeping & Room Management', 'OPERATIONAL_INDUSTRY', '72', 'ACTIVE'),
  ('MCR-ERP-menu_management', 'MCAT-ERP-MODULES-1', 'menu_management', 'Menu & Recipe Management', 'OPERATIONAL_INDUSTRY', '72', 'ACTIVE'),
  ('MCR-ERP-academic', 'MCAT-ERP-MODULES-1', 'academic', 'Academic Records & Student Management', 'OPERATIONAL_INDUSTRY', '61', 'ACTIVE'),
  ('MCR-ERP-admissions', 'MCAT-ERP-MODULES-1', 'admissions', 'Admissions & Enrolment', 'OPERATIONAL_INDUSTRY', '61', 'ACTIVE'),
  ('MCR-ERP-fundraising', 'MCAT-ERP-MODULES-1', 'fundraising', 'Fundraising & Donor Management', 'OPERATIONAL_INDUSTRY', '61, 71, 81', 'ACTIVE'),
  ('MCR-ERP-public_safety', 'MCAT-ERP-MODULES-1', 'public_safety', 'Public Safety & Incident Management', 'OPERATIONAL_INDUSTRY', '92', 'ACTIVE'),
  ('MCR-ERP-permitting', 'MCAT-ERP-MODULES-1', 'permitting', 'Permitting & Licensing', 'OPERATIONAL_INDUSTRY', '92, 23', 'ACTIVE'),
  ('MCR-ERP-land_management', 'MCAT-ERP-MODULES-1', 'land_management', 'Land & Property Management', 'OPERATIONAL_INDUSTRY', '53, 92', 'ACTIVE'),
  ('MCR-ERP-agronomy', 'MCAT-ERP-MODULES-1', 'agronomy', 'Crop & Field Management', 'OPERATIONAL_INDUSTRY', '11', 'ACTIVE'),
  ('MCR-ERP-livestock', 'MCAT-ERP-MODULES-1', 'livestock', 'Livestock & Herd Management', 'OPERATIONAL_INDUSTRY', '11', 'ACTIVE'),
  ('MCR-ERP-forestry', 'MCAT-ERP-MODULES-1', 'forestry', 'Forestry & Timber Management', 'OPERATIONAL_INDUSTRY', '11', 'ACTIVE'),
  ('MCR-ERP-mining_ops', 'MCAT-ERP-MODULES-1', 'mining_ops', 'Mining Operations', 'OPERATIONAL_INDUSTRY', '21', 'ACTIVE'),
  ('MCR-ERP-well_management', 'MCAT-ERP-MODULES-1', 'well_management', 'Well & Reservoir Management', 'OPERATIONAL_INDUSTRY', '21', 'ACTIVE'),
  ('MCR-ERP-grid_management', 'MCAT-ERP-MODULES-1', 'grid_management', 'Grid & Network Management', 'OPERATIONAL_INDUSTRY', '22', 'ACTIVE'),
  ('MCR-ERP-metering', 'MCAT-ERP-MODULES-1', 'metering', 'Metering & Billing (Utilities)', 'OPERATIONAL_INDUSTRY', '22', 'ACTIVE');

INSERT INTO business_classification_capability_guidance
  (classification_value_id, capability_reference_id, source_symbol, source_state)
VALUES
  ('BCV-NAICS-2022-11', 'MCR-ERP-finance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-finance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-finance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-finance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-finance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-finance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-finance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-finance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-finance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-finance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-finance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-finance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-finance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-finance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-finance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-finance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-finance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-finance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-finance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-finance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-hr', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-hr', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-hr', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-hr', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-hr', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-hr', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-hr', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-hr', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-hr', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-hr', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-hr', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-hr', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-hr', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-hr', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-hr', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-hr', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-hr', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-hr', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-hr', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-hr', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-payroll', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-payroll', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-payroll', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-payroll', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-payroll', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-payroll', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-payroll', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-payroll', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-payroll', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-payroll', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-payroll', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-payroll', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-payroll', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-payroll', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-payroll', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-payroll', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-payroll', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-payroll', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-payroll', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-payroll', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-crm', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-crm', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-crm', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-crm', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-crm', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-crm', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-crm', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-crm', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-crm', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-crm', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-crm', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-crm', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-crm', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-crm', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-crm', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-crm', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-crm', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-crm', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-crm', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-crm', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-documents', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-documents', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-documents', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-documents', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-documents', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-documents', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-documents', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-documents', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-documents', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-documents', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-documents', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-documents', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-documents', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-documents', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-documents', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-documents', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-documents', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-documents', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-documents', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-documents', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-intranet', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-intranet', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-intranet', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-intranet', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-intranet', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-intranet', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-intranet', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-intranet', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-intranet', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-intranet', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-intranet', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-intranet', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-intranet', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-intranet', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-intranet', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-intranet', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-intranet', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-intranet', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-intranet', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-intranet', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-admin', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-admin', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-admin', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-admin', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-admin', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-admin', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-admin', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-admin', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-admin', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-admin', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-admin', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-admin', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-admin', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-admin', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-admin', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-admin', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-admin', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-admin', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-admin', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-admin', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-analytics', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-analytics', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-analytics', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-analytics', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-analytics', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-analytics', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-analytics', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-analytics', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-analytics', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-analytics', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-analytics', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-analytics', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-analytics', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-analytics', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-analytics', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-analytics', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-analytics', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-analytics', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-analytics', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-analytics', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-projects', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-projects', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-projects', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-projects', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-projects', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-projects', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-projects', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-projects', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-projects', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-projects', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-projects', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-projects', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-projects', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-projects', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-projects', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-projects', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-projects', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-projects', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-projects', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-projects', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-job_costing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-job_costing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-job_costing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-job_costing', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-job_costing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-job_costing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-job_costing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-job_costing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-job_costing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-job_costing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-job_costing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-job_costing', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-job_costing', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-job_costing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-job_costing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-job_costing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-job_costing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-job_costing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-job_costing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-job_costing', '—', 'HIDDEN_NOT_APPLICABLE');

INSERT INTO business_classification_capability_guidance
  (classification_value_id, capability_reference_id, source_symbol, source_state)
VALUES
  ('BCV-NAICS-2022-11', 'MCR-ERP-field_service', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-field_service', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-field_service', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-field_service', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-field_service', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-field_service', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-field_service', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-field_service', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-field_service', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-field_service', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-field_service', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-field_service', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-field_service', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-field_service', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-field_service', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-field_service', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-field_service', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-field_service', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-field_service', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-field_service', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-inventory', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-inventory', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-inventory', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-inventory', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-inventory', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-inventory', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-inventory', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-inventory', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-inventory', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-inventory', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-inventory', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-inventory', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-inventory', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-inventory', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-inventory', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-inventory', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-inventory', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-inventory', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-inventory', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-inventory', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-procurement', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-procurement', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-procurement', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-procurement', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-procurement', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-procurement', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-procurement', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-procurement', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-procurement', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-procurement', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-procurement', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-procurement', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-procurement', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-procurement', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-procurement', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-procurement', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-procurement', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-procurement', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-procurement', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-procurement', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-sales_orders', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-sales_orders', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-sales_orders', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-sales_orders', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-sales_orders', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-sales_orders', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-sales_orders', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-sales_orders', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-sales_orders', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-sales_orders', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-sales_orders', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-sales_orders', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-sales_orders', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-sales_orders', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-sales_orders', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-sales_orders', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-sales_orders', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-sales_orders', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-sales_orders', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-sales_orders', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-pos', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-pos', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-pos', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-pos', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-pos', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-pos', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-pos', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-pos', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-pos', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-pos', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-pos', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-pos', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-pos', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-pos', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-pos', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-pos', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-pos', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-pos', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-pos', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-pos', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-manufacturing', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-manufacturing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-manufacturing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-manufacturing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-manufacturing', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-manufacturing', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-manufacturing', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-manufacturing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-manufacturing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-manufacturing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-manufacturing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-manufacturing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-manufacturing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-manufacturing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-manufacturing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-manufacturing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-manufacturing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-manufacturing', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-manufacturing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-manufacturing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-quality', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-quality', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-quality', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-quality', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-quality', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-quality', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-quality', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-quality', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-quality', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-quality', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-quality', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-quality', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-quality', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-quality', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-quality', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-quality', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-quality', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-quality', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-quality', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-quality', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-maintenance', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-maintenance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-maintenance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-maintenance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-maintenance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-maintenance', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-maintenance', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-maintenance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-maintenance', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-maintenance', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-maintenance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-maintenance', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-maintenance', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-maintenance', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-maintenance', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-maintenance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-maintenance', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-maintenance', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-maintenance', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-maintenance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-fleet', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-fleet', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-fleet', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-fleet', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-fleet', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-fleet', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-fleet', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-fleet', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-fleet', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-fleet', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-fleet', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-fleet', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-fleet', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-fleet', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-fleet', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-fleet', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-fleet', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-fleet', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-fleet', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-fleet', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-warehouse', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-warehouse', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-warehouse', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-warehouse', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-warehouse', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-warehouse', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-warehouse', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-warehouse', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-warehouse', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-warehouse', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-warehouse', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-warehouse', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-warehouse', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-warehouse', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-warehouse', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-warehouse', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-warehouse', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-warehouse', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-warehouse', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-warehouse', '—', 'HIDDEN_NOT_APPLICABLE');

INSERT INTO business_classification_capability_guidance
  (classification_value_id, capability_reference_id, source_symbol, source_state)
VALUES
  ('BCV-NAICS-2022-11', 'MCR-ERP-supply_chain', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-supply_chain', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-supply_chain', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-supply_chain', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-supply_chain', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-supply_chain', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-supply_chain', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-supply_chain', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-supply_chain', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-supply_chain', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-supply_chain', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-supply_chain', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-supply_chain', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-supply_chain', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-supply_chain', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-supply_chain', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-supply_chain', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-supply_chain', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-supply_chain', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-supply_chain', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-clinical', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-clinical', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-clinical', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-clinical', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-clinical', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-clinical', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-clinical', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-clinical', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-clinical', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-clinical', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-clinical', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-clinical', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-clinical', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-clinical', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-clinical', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-clinical', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-clinical', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-clinical', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-clinical', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-clinical', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-scheduling', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-scheduling', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-scheduling', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-scheduling', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-scheduling', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-scheduling', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-scheduling', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-scheduling', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-scheduling', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-scheduling', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-scheduling', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-scheduling', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-scheduling', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-scheduling', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-scheduling', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-scheduling', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-scheduling', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-scheduling', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-scheduling', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-scheduling', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-patient_billing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-patient_billing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-patient_billing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-patient_billing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-patient_billing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-patient_billing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-patient_billing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-patient_billing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-patient_billing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-patient_billing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-patient_billing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-patient_billing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-patient_billing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-patient_billing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-patient_billing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-patient_billing', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-patient_billing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-patient_billing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-patient_billing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-patient_billing', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-compliance', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-compliance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-compliance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-compliance', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-compliance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-compliance', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-compliance', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-compliance', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-compliance', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-compliance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-compliance', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-compliance', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-compliance', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-compliance', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-compliance', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-compliance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-compliance', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-compliance', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-compliance', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-compliance', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-risk', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-risk', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-risk', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-risk', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-risk', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-risk', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-risk', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-risk', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-risk', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-risk', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-risk', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-risk', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-risk', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-risk', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-risk', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-risk', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-risk', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-risk', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-risk', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-risk', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-subscriptions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-subscriptions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-subscriptions', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-subscriptions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-subscriptions', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-subscriptions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-subscriptions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-subscriptions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-subscriptions', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-subscriptions', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-subscriptions', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-subscriptions', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-subscriptions', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-subscriptions', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-subscriptions', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-subscriptions', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-subscriptions', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-subscriptions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-subscriptions', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-subscriptions', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-time_tracking', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-time_tracking', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-time_tracking', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-time_tracking', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-time_tracking', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-time_tracking', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-time_tracking', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-time_tracking', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-time_tracking', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-time_tracking', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-time_tracking', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-time_tracking', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-time_tracking', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-time_tracking', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-time_tracking', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-time_tracking', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-time_tracking', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-time_tracking', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-time_tracking', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-time_tracking', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-resource_planning', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-resource_planning', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-resource_planning', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-resource_planning', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-resource_planning', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-resource_planning', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-resource_planning', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-resource_planning', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-resource_planning', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-resource_planning', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-resource_planning', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-resource_planning', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-resource_planning', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-resource_planning', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-resource_planning', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-resource_planning', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-resource_planning', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-resource_planning', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-resource_planning', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-resource_planning', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-ecommerce', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-ecommerce', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-ecommerce', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-ecommerce', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-ecommerce', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-ecommerce', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-ecommerce', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-ecommerce', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-ecommerce', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-ecommerce', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-ecommerce', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-ecommerce', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-ecommerce', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-ecommerce', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-ecommerce', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-ecommerce', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-ecommerce', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-ecommerce', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-ecommerce', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-ecommerce', '—', 'HIDDEN_NOT_APPLICABLE');

INSERT INTO business_classification_capability_guidance
  (classification_value_id, capability_reference_id, source_symbol, source_state)
VALUES
  ('BCV-NAICS-2022-11', 'MCR-ERP-loyalty', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-loyalty', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-loyalty', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-loyalty', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-loyalty', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-loyalty', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-loyalty', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-loyalty', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-loyalty', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-loyalty', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-loyalty', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-loyalty', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-loyalty', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-loyalty', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-loyalty', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-loyalty', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-loyalty', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-loyalty', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-loyalty', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-loyalty', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-reservations', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-reservations', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-reservations', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-reservations', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-reservations', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-reservations', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-reservations', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-reservations', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-reservations', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-reservations', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-reservations', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-reservations', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-reservations', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-reservations', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-reservations', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-reservations', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-reservations', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-reservations', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-reservations', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-reservations', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-housekeeping', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-housekeeping', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-housekeeping', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-housekeeping', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-housekeeping', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-housekeeping', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-housekeeping', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-housekeeping', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-housekeeping', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-housekeeping', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-housekeeping', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-housekeeping', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-housekeeping', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-housekeeping', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-housekeeping', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-housekeeping', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-housekeeping', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-housekeeping', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-housekeeping', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-housekeeping', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-menu_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-menu_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-menu_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-menu_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-menu_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-menu_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-menu_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-menu_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-menu_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-menu_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-menu_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-menu_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-menu_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-menu_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-menu_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-menu_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-menu_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-menu_management', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-menu_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-menu_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-academic', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-academic', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-academic', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-academic', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-academic', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-academic', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-academic', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-academic', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-academic', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-academic', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-academic', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-academic', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-academic', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-academic', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-academic', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-academic', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-academic', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-academic', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-academic', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-academic', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-admissions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-admissions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-admissions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-admissions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-admissions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-admissions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-admissions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-admissions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-admissions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-admissions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-admissions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-admissions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-admissions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-admissions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-admissions', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-admissions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-admissions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-admissions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-admissions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-admissions', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-fundraising', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-fundraising', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-fundraising', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-fundraising', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-fundraising', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-fundraising', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-fundraising', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-fundraising', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-fundraising', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-fundraising', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-fundraising', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-fundraising', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-fundraising', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-fundraising', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-fundraising', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-fundraising', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-fundraising', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-fundraising', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-fundraising', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-fundraising', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-public_safety', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-public_safety', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-public_safety', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-public_safety', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-public_safety', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-public_safety', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-public_safety', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-public_safety', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-public_safety', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-public_safety', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-public_safety', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-public_safety', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-public_safety', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-public_safety', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-public_safety', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-public_safety', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-public_safety', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-public_safety', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-public_safety', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-public_safety', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-permitting', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-permitting', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-permitting', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-permitting', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-permitting', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-permitting', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-permitting', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-permitting', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-permitting', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-permitting', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-permitting', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-permitting', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-permitting', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-permitting', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-permitting', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-permitting', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-permitting', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-permitting', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-permitting', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-permitting', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-land_management', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-land_management', '○', 'AVAILABLE_DISABLED'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-land_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-land_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-land_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-land_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-land_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-land_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-land_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-land_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-land_management', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-land_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-land_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-land_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-land_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-land_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-land_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-land_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-land_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-land_management', '●', 'DEFAULT_ENABLED');

INSERT INTO business_classification_capability_guidance
  (classification_value_id, capability_reference_id, source_symbol, source_state)
VALUES
  ('BCV-NAICS-2022-11', 'MCR-ERP-agronomy', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-agronomy', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-agronomy', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-agronomy', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-agronomy', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-agronomy', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-agronomy', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-agronomy', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-agronomy', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-agronomy', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-agronomy', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-agronomy', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-agronomy', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-agronomy', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-agronomy', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-agronomy', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-agronomy', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-agronomy', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-agronomy', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-agronomy', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-livestock', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-livestock', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-livestock', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-livestock', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-livestock', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-livestock', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-livestock', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-livestock', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-livestock', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-livestock', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-livestock', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-livestock', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-livestock', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-livestock', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-livestock', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-livestock', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-livestock', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-livestock', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-livestock', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-livestock', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-forestry', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-forestry', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-forestry', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-forestry', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-forestry', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-forestry', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-forestry', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-forestry', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-forestry', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-forestry', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-forestry', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-forestry', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-forestry', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-forestry', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-forestry', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-forestry', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-forestry', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-forestry', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-forestry', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-forestry', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-mining_ops', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-mining_ops', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-mining_ops', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-mining_ops', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-mining_ops', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-mining_ops', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-mining_ops', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-mining_ops', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-mining_ops', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-mining_ops', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-mining_ops', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-mining_ops', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-mining_ops', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-mining_ops', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-mining_ops', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-mining_ops', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-mining_ops', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-mining_ops', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-mining_ops', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-mining_ops', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-well_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-well_management', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-well_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-well_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-well_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-well_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-well_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-well_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-well_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-well_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-well_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-well_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-well_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-well_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-well_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-well_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-well_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-well_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-well_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-well_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-grid_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-grid_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-grid_management', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-grid_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-grid_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-grid_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-grid_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-grid_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-grid_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-grid_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-grid_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-grid_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-grid_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-grid_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-grid_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-grid_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-grid_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-grid_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-grid_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-grid_management', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-11', 'MCR-ERP-metering', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-21', 'MCR-ERP-metering', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-22', 'MCR-ERP-metering', '●', 'DEFAULT_ENABLED'),
  ('BCV-NAICS-2022-23', 'MCR-ERP-metering', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-31-33', 'MCR-ERP-metering', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-42', 'MCR-ERP-metering', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-44-45', 'MCR-ERP-metering', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-48-49', 'MCR-ERP-metering', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-51', 'MCR-ERP-metering', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-52', 'MCR-ERP-metering', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-53', 'MCR-ERP-metering', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-54', 'MCR-ERP-metering', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-55', 'MCR-ERP-metering', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-56', 'MCR-ERP-metering', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-61', 'MCR-ERP-metering', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-62', 'MCR-ERP-metering', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-71', 'MCR-ERP-metering', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-72', 'MCR-ERP-metering', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-81', 'MCR-ERP-metering', '—', 'HIDDEN_NOT_APPLICABLE'),
  ('BCV-NAICS-2022-92', 'MCR-ERP-metering', '—', 'HIDDEN_NOT_APPLICABLE');
