-- NuBlox V3 MySQL
-- 0032: F04 Corporate Development & M&A canonical runtime.

CREATE TABLE development_opportunities (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  opportunity_ref VARCHAR(191) NOT NULL,
  opportunity_type VARCHAR(64) NOT NULL,
  title VARCHAR(500) NOT NULL,
  development_thesis TEXT NOT NULL,
  source_type VARCHAR(64) NOT NULL,
  source_reference VARCHAR(500) NULL,
  target_party_id VARCHAR(36) NULL,
  sponsor_party_id VARCHAR(36) NOT NULL,
  scope_description TEXT NOT NULL,
  indicative_value_min DECIMAL(30,10) NULL,
  indicative_value_max DECIMAL(30,10) NULL,
  currency_id VARCHAR(36) NULL,
  status VARCHAR(32) NOT NULL,
  aggregate_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_by_party_id VARCHAR(36) NOT NULL,
  created_at VARCHAR(32) NOT NULL,
  updated_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_dev_opportunity_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_dev_opportunity_target_party FOREIGN KEY (target_party_id) REFERENCES parties(id),
  CONSTRAINT fk_dev_opportunity_sponsor FOREIGN KEY (sponsor_party_id) REFERENCES parties(id),
  CONSTRAINT fk_dev_opportunity_currency FOREIGN KEY (currency_id) REFERENCES reference_currencies(id),
  CONSTRAINT fk_dev_opportunity_creator FOREIGN KEY (created_by_party_id) REFERENCES parties(id),
  UNIQUE KEY uq_dev_opportunity_ref (tenant_id, opportunity_ref),
  INDEX idx_dev_opportunity_status (tenant_id, status, opportunity_type, updated_at),
  INDEX idx_dev_opportunity_target (tenant_id, target_party_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE development_opportunity_assessments (
  id VARCHAR(36) PRIMARY KEY,
  opportunity_id VARCHAR(36) NOT NULL,
  assessment_type VARCHAR(64) NOT NULL,
  strategic_fit_rating VARCHAR(32) NULL,
  recommendation VARCHAR(32) NOT NULL,
  assessment_summary TEXT NOT NULL,
  evidence_reference VARCHAR(500) NULL,
  assessed_by_party_id VARCHAR(36) NOT NULL,
  assessed_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_dev_opp_assessment_opportunity FOREIGN KEY (opportunity_id) REFERENCES development_opportunities(id),
  CONSTRAINT fk_dev_opp_assessment_actor FOREIGN KEY (assessed_by_party_id) REFERENCES parties(id),
  INDEX idx_dev_opp_assessment (opportunity_id, assessment_type, assessed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE development_appraisals (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  opportunity_id VARCHAR(36) NOT NULL,
  appraisal_ref VARCHAR(191) NOT NULL,
  scenario_name VARCHAR(255) NOT NULL,
  as_of_at VARCHAR(32) NOT NULL,
  source_basis_json JSON NOT NULL,
  assumptions_json JSON NOT NULL,
  synergy_assumptions_json JSON NOT NULL,
  valuation_metrics_json JSON NOT NULL,
  sensitivity_json JSON NOT NULL,
  status VARCHAR(32) NOT NULL,
  aggregate_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  reviewed_by_party_id VARCHAR(36) NULL,
  reviewed_at VARCHAR(32) NULL,
  approved_snapshot_at VARCHAR(32) NULL,
  supersedes_appraisal_id VARCHAR(36) NULL,
  created_by_party_id VARCHAR(36) NOT NULL,
  created_at VARCHAR(32) NOT NULL,
  updated_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_dev_appraisal_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_dev_appraisal_opportunity FOREIGN KEY (opportunity_id) REFERENCES development_opportunities(id),
  CONSTRAINT fk_dev_appraisal_reviewer FOREIGN KEY (reviewed_by_party_id) REFERENCES parties(id),
  CONSTRAINT fk_dev_appraisal_supersedes FOREIGN KEY (supersedes_appraisal_id) REFERENCES development_appraisals(id),
  CONSTRAINT fk_dev_appraisal_creator FOREIGN KEY (created_by_party_id) REFERENCES parties(id),
  UNIQUE KEY uq_dev_appraisal_ref (tenant_id, appraisal_ref),
  INDEX idx_dev_appraisal_opportunity (tenant_id, opportunity_id, status, as_of_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE legal_matters (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  matter_ref VARCHAR(191) NOT NULL,
  matter_type VARCHAR(64) NOT NULL,
  title VARCHAR(500) NOT NULL,
  subject_type VARCHAR(64) NOT NULL,
  subject_id VARCHAR(191) NOT NULL,
  subject_version VARCHAR(64) NULL,
  scope_summary TEXT NOT NULL,
  owner_party_id VARCHAR(36) NOT NULL,
  counsel_party_id VARCHAR(36) NULL,
  jurisdiction_id VARCHAR(36) NULL,
  privilege_classification VARCHAR(64) NOT NULL,
  confidentiality_classification VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  aggregate_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  opened_at VARCHAR(32) NOT NULL,
  closed_at VARCHAR(32) NULL,
  created_by_party_id VARCHAR(36) NOT NULL,
  created_at VARCHAR(32) NOT NULL,
  updated_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_legal_matter_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_legal_matter_owner FOREIGN KEY (owner_party_id) REFERENCES parties(id),
  CONSTRAINT fk_legal_matter_counsel FOREIGN KEY (counsel_party_id) REFERENCES parties(id),
  CONSTRAINT fk_legal_matter_jurisdiction FOREIGN KEY (jurisdiction_id) REFERENCES reference_jurisdictions(id),
  CONSTRAINT fk_legal_matter_creator FOREIGN KEY (created_by_party_id) REFERENCES parties(id),
  UNIQUE KEY uq_legal_matter_ref (tenant_id, matter_ref),
  INDEX idx_legal_matter_subject (tenant_id, subject_type, subject_id, status),
  INDEX idx_legal_matter_owner (tenant_id, owner_party_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE legal_matter_access (
  matter_id VARCHAR(36) NOT NULL,
  party_id VARCHAR(36) NOT NULL,
  access_role VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  granted_by_party_id VARCHAR(36) NOT NULL,
  granted_at VARCHAR(32) NOT NULL,
  revoked_by_party_id VARCHAR(36) NULL,
  revoked_at VARCHAR(32) NULL,
  PRIMARY KEY (matter_id, party_id),
  CONSTRAINT fk_legal_matter_access_matter FOREIGN KEY (matter_id) REFERENCES legal_matters(id),
  CONSTRAINT fk_legal_matter_access_party FOREIGN KEY (party_id) REFERENCES parties(id),
  CONSTRAINT fk_legal_matter_access_grantor FOREIGN KEY (granted_by_party_id) REFERENCES parties(id),
  CONSTRAINT fk_legal_matter_access_revoker FOREIGN KEY (revoked_by_party_id) REFERENCES parties(id),
  INDEX idx_legal_matter_access_party (party_id, status, access_role)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE legal_matter_workstreams (
  id VARCHAR(36) PRIMARY KEY,
  matter_id VARCHAR(36) NOT NULL,
  workstream_type VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  risk_rating VARCHAR(32) NULL,
  findings_summary TEXT NULL,
  conclusion TEXT NULL,
  evidence_reference VARCHAR(500) NULL,
  owner_party_id VARCHAR(36) NOT NULL,
  aggregate_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_at VARCHAR(32) NOT NULL,
  updated_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_legal_workstream_matter FOREIGN KEY (matter_id) REFERENCES legal_matters(id),
  CONSTRAINT fk_legal_workstream_owner FOREIGN KEY (owner_party_id) REFERENCES parties(id),
  UNIQUE KEY uq_legal_workstream_type (matter_id, workstream_type),
  INDEX idx_legal_workstream_status (matter_id, status, workstream_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE business_cases (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  case_ref VARCHAR(191) NOT NULL,
  case_type VARCHAR(64) NOT NULL,
  title VARCHAR(500) NOT NULL,
  sponsor_party_id VARCHAR(36) NOT NULL,
  primary_party_id VARCHAR(36) NULL,
  development_opportunity_id VARCHAR(36) NULL,
  status VARCHAR(32) NOT NULL,
  aggregate_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  current_version_no INT UNSIGNED NOT NULL DEFAULT 1,
  approval_decision_id VARCHAR(36) NULL,
  approved_at VARCHAR(32) NULL,
  closed_at VARCHAR(32) NULL,
  created_by_party_id VARCHAR(36) NOT NULL,
  created_at VARCHAR(32) NOT NULL,
  updated_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_business_case_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_business_case_sponsor FOREIGN KEY (sponsor_party_id) REFERENCES parties(id),
  CONSTRAINT fk_business_case_primary_party FOREIGN KEY (primary_party_id) REFERENCES parties(id),
  CONSTRAINT fk_business_case_opportunity FOREIGN KEY (development_opportunity_id) REFERENCES development_opportunities(id),
  CONSTRAINT fk_business_case_decision FOREIGN KEY (approval_decision_id) REFERENCES work_decisions(id),
  CONSTRAINT fk_business_case_creator FOREIGN KEY (created_by_party_id) REFERENCES parties(id),
  UNIQUE KEY uq_business_case_ref (tenant_id, case_ref),
  INDEX idx_business_case_status (tenant_id, case_type, status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE business_case_versions (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  business_case_id VARCHAR(36) NOT NULL,
  version_no INT UNSIGNED NOT NULL,
  lifecycle_status VARCHAR(32) NOT NULL,
  objectives_need TEXT NOT NULL,
  options_json JSON NOT NULL,
  benefits_json JSON NOT NULL,
  cost_funding_basis_json JSON NOT NULL,
  risks_json JSON NOT NULL,
  assumptions_json JSON NOT NULL,
  transaction_structure_json JSON NOT NULL,
  negotiated_terms_json JSON NOT NULL,
  recommendation TEXT NOT NULL,
  appraisal_id VARCHAR(36) NULL,
  legal_matter_id VARCHAR(36) NULL,
  created_by_party_id VARCHAR(36) NOT NULL,
  created_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_business_case_version_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_business_case_version_root FOREIGN KEY (business_case_id) REFERENCES business_cases(id),
  CONSTRAINT fk_business_case_version_appraisal FOREIGN KEY (appraisal_id) REFERENCES development_appraisals(id),
  CONSTRAINT fk_business_case_version_legal FOREIGN KEY (legal_matter_id) REFERENCES legal_matters(id),
  CONSTRAINT fk_business_case_version_creator FOREIGN KEY (created_by_party_id) REFERENCES parties(id),
  UNIQUE KEY uq_business_case_version (business_case_id, version_no),
  INDEX idx_business_case_version_status (tenant_id, business_case_id, lifecycle_status, version_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE business_case_agreements (
  id VARCHAR(36) PRIMARY KEY,
  business_case_id VARCHAR(36) NOT NULL,
  agreement_role VARCHAR(64) NOT NULL,
  subject_type VARCHAR(64) NOT NULL,
  subject_id VARCHAR(191) NOT NULL,
  subject_version VARCHAR(64) NULL,
  execution_status VARCHAR(32) NOT NULL,
  execution_reference VARCHAR(500) NULL,
  executed_at VARCHAR(32) NULL,
  recorded_by_party_id VARCHAR(36) NOT NULL,
  recorded_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_business_case_agreement_case FOREIGN KEY (business_case_id) REFERENCES business_cases(id),
  CONSTRAINT fk_business_case_agreement_actor FOREIGN KEY (recorded_by_party_id) REFERENCES parties(id),
  UNIQUE KEY uq_business_case_agreement (business_case_id, agreement_role, subject_type, subject_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE transformation_initiatives (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  initiative_ref VARCHAR(191) NOT NULL,
  initiative_type VARCHAR(64) NOT NULL,
  title VARCHAR(500) NOT NULL,
  purpose_outcomes TEXT NOT NULL,
  sponsor_party_id VARCHAR(36) NOT NULL,
  owner_party_id VARCHAR(36) NOT NULL,
  affected_scope TEXT NOT NULL,
  benefits_summary TEXT NOT NULL,
  impacts_summary TEXT NOT NULL,
  readiness_criteria TEXT NOT NULL,
  adoption_criteria TEXT NOT NULL,
  source_subject_type VARCHAR(64) NULL,
  source_subject_id VARCHAR(191) NULL,
  status VARCHAR(32) NOT NULL,
  aggregate_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_by_party_id VARCHAR(36) NOT NULL,
  created_at VARCHAR(32) NOT NULL,
  updated_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_transformation_initiative_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_transformation_initiative_sponsor FOREIGN KEY (sponsor_party_id) REFERENCES parties(id),
  CONSTRAINT fk_transformation_initiative_owner FOREIGN KEY (owner_party_id) REFERENCES parties(id),
  CONSTRAINT fk_transformation_initiative_creator FOREIGN KEY (created_by_party_id) REFERENCES parties(id),
  UNIQUE KEY uq_transformation_initiative_ref (tenant_id, initiative_ref),
  INDEX idx_transformation_initiative_status (tenant_id, initiative_type, status, updated_at),
  INDEX idx_transformation_initiative_source (tenant_id, source_subject_type, source_subject_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE transformation_initiative_workstreams (
  id VARCHAR(36) PRIMARY KEY,
  initiative_id VARCHAR(36) NOT NULL,
  workstream_type VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  owner_party_id VARCHAR(36) NOT NULL,
  scope_summary TEXT NOT NULL,
  success_criteria TEXT NOT NULL,
  status VARCHAR(32) NOT NULL,
  progress_percent DECIMAL(9,4) NOT NULL DEFAULT 0,
  aggregate_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_at VARCHAR(32) NOT NULL,
  updated_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_transformation_workstream_initiative FOREIGN KEY (initiative_id) REFERENCES transformation_initiatives(id),
  CONSTRAINT fk_transformation_workstream_owner FOREIGN KEY (owner_party_id) REFERENCES parties(id),
  UNIQUE KEY uq_transformation_workstream (initiative_id, workstream_type),
  INDEX idx_transformation_workstream_status (initiative_id, status, workstream_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
