-- NuBlox V3 MySQL
-- 0038: functional governance, workforce capability and deployment runtime.
-- Persists the Person -> Worker Relationship -> Position -> Job Profile chain and
-- the governed Function/Delivery Domain -> Job -> Deployment model.

CREATE TABLE worker_relationships (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  person_party_id VARCHAR(36) NOT NULL,
  organisation_party_id VARCHAR(36) NOT NULL,
  relationship_type VARCHAR(64) NOT NULL,
  jurisdiction_code VARCHAR(16) NULL,
  terms_reference VARCHAR(500) NULL,
  status VARCHAR(32) NOT NULL,
  version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  valid_from VARCHAR(32) NOT NULL,
  valid_to VARCHAR(32) NULL,
  created_at VARCHAR(32) NOT NULL,
  updated_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_worker_relationship_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_worker_relationship_person FOREIGN KEY (person_party_id) REFERENCES persons(party_id),
  CONSTRAINT fk_worker_relationship_org FOREIGN KEY (organisation_party_id) REFERENCES organisations(party_id),
  INDEX idx_worker_relationship_person (tenant_id, person_party_id, status, valid_from, valid_to),
  INDEX idx_worker_relationship_org (tenant_id, organisation_party_id, status, valid_from, valid_to)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE job_profiles (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  job_code VARCHAR(191) NOT NULL,
  name VARCHAR(255) NOT NULL,
  job_family VARCHAR(191) NULL,
  job_level VARCHAR(64) NULL,
  sector_domain VARCHAR(191) NULL,
  purpose TEXT NULL,
  source_reference VARCHAR(500) NULL,
  status VARCHAR(32) NOT NULL,
  version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  valid_from VARCHAR(32) NOT NULL,
  valid_to VARCHAR(32) NULL,
  created_at VARCHAR(32) NOT NULL,
  updated_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_job_profile_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  UNIQUE KEY uq_job_profile_code (tenant_id, job_code),
  INDEX idx_job_profile_domain (tenant_id, sector_domain, status, name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE positions (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  position_code VARCHAR(191) NOT NULL,
  name VARCHAR(255) NOT NULL,
  organisation_unit_id VARCHAR(36) NULL,
  accountable_legal_entity_party_id VARCHAR(36) NULL,
  job_profile_id VARCHAR(36) NOT NULL,
  capacity_fte DECIMAL(7,4) NOT NULL DEFAULT 1.0000,
  location_type VARCHAR(64) NULL,
  location_id VARCHAR(191) NULL,
  status VARCHAR(32) NOT NULL,
  version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  valid_from VARCHAR(32) NOT NULL,
  valid_to VARCHAR(32) NULL,
  created_at VARCHAR(32) NOT NULL,
  updated_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_position_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_position_org_unit FOREIGN KEY (organisation_unit_id) REFERENCES organisation_units(id),
  CONSTRAINT fk_position_legal_entity FOREIGN KEY (accountable_legal_entity_party_id) REFERENCES legal_entities(party_id),
  CONSTRAINT fk_position_job_profile FOREIGN KEY (job_profile_id) REFERENCES job_profiles(id),
  UNIQUE KEY uq_position_code (tenant_id, position_code),
  INDEX idx_position_job (tenant_id, job_profile_id, status),
  INDEX idx_position_org (tenant_id, organisation_unit_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE position_assignments (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  position_id VARCHAR(36) NOT NULL,
  worker_relationship_id VARCHAR(36) NOT NULL,
  person_party_id VARCHAR(36) NOT NULL,
  assignment_type VARCHAR(64) NOT NULL,
  allocation_percent DECIMAL(7,4) NOT NULL DEFAULT 100.0000,
  status VARCHAR(32) NOT NULL,
  version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  valid_from VARCHAR(32) NOT NULL,
  valid_to VARCHAR(32) NULL,
  created_at VARCHAR(32) NOT NULL,
  updated_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_position_assignment_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_position_assignment_position FOREIGN KEY (position_id) REFERENCES positions(id),
  CONSTRAINT fk_position_assignment_worker FOREIGN KEY (worker_relationship_id) REFERENCES worker_relationships(id),
  CONSTRAINT fk_position_assignment_person FOREIGN KEY (person_party_id) REFERENCES persons(party_id),
  INDEX idx_position_assignment_position (tenant_id, position_id, status, valid_from, valid_to),
  INDEX idx_position_assignment_person (tenant_id, person_party_id, status, valid_from, valid_to)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE competence_definitions (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  competence_code VARCHAR(191) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT NULL,
  context_type VARCHAR(64) NULL,
  level_scale_json JSON NULL,
  evidence_requirements_json JSON NULL,
  reassessment_rule_json JSON NULL,
  status VARCHAR(32) NOT NULL,
  version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  valid_from VARCHAR(32) NOT NULL,
  valid_to VARCHAR(32) NULL,
  created_at VARCHAR(32) NOT NULL,
  updated_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_competence_definition_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  UNIQUE KEY uq_competence_definition_code (tenant_id, competence_code),
  INDEX idx_competence_definition_status (tenant_id, status, name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE job_competence_requirements (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  job_profile_id VARCHAR(36) NOT NULL,
  competence_definition_id VARCHAR(36) NOT NULL,
  required_level VARCHAR(64) NOT NULL,
  context_type VARCHAR(64) NULL,
  context_id VARCHAR(191) NULL,
  mandatory BOOLEAN NOT NULL DEFAULT TRUE,
  status VARCHAR(32) NOT NULL,
  valid_from VARCHAR(32) NOT NULL,
  valid_to VARCHAR(32) NULL,
  created_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_job_competence_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_job_competence_job FOREIGN KEY (job_profile_id) REFERENCES job_profiles(id),
  CONSTRAINT fk_job_competence_definition FOREIGN KEY (competence_definition_id) REFERENCES competence_definitions(id),
  UNIQUE KEY uq_job_competence_requirement
    (tenant_id, job_profile_id, competence_definition_id, context_type, context_id),
  INDEX idx_job_competence_job (tenant_id, job_profile_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE person_competences (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  person_party_id VARCHAR(36) NOT NULL,
  competence_definition_id VARCHAR(36) NOT NULL,
  assessed_level VARCHAR(64) NOT NULL,
  assessor_party_id VARCHAR(36) NULL,
  evidence_subject_type VARCHAR(128) NULL,
  evidence_subject_id VARCHAR(191) NULL,
  status VARCHAR(32) NOT NULL,
  version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  assessed_at VARCHAR(32) NOT NULL,
  valid_from VARCHAR(32) NOT NULL,
  valid_to VARCHAR(32) NULL,
  created_at VARCHAR(32) NOT NULL,
  updated_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_person_competence_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_person_competence_person FOREIGN KEY (person_party_id) REFERENCES persons(party_id),
  CONSTRAINT fk_person_competence_definition FOREIGN KEY (competence_definition_id) REFERENCES competence_definitions(id),
  CONSTRAINT fk_person_competence_assessor FOREIGN KEY (assessor_party_id) REFERENCES parties(id),
  INDEX idx_person_competence_person (tenant_id, person_party_id, status, valid_from, valid_to),
  INDEX idx_person_competence_definition (tenant_id, competence_definition_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE functional_definitions (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  function_code VARCHAR(32) NOT NULL,
  function_type VARCHAR(32) NOT NULL,
  name VARCHAR(255) NOT NULL,
  owner_position_id VARCHAR(36) NULL,
  status VARCHAR(32) NOT NULL,
  current_version_no INT UNSIGNED NOT NULL DEFAULT 1,
  created_at VARCHAR(32) NOT NULL,
  updated_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_functional_definition_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_functional_definition_owner FOREIGN KEY (owner_position_id) REFERENCES positions(id),
  UNIQUE KEY uq_functional_definition_code (tenant_id, function_code),
  INDEX idx_functional_definition_type (tenant_id, function_type, status, name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE functional_definition_versions (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  functional_definition_id VARCHAR(36) NOT NULL,
  version_no INT UNSIGNED NOT NULL,
  baseline_label VARCHAR(191) NULL,
  purpose TEXT NOT NULL,
  scope_text TEXT NULL,
  governance_json JSON NOT NULL,
  delivery_json JSON NOT NULL,
  deployment_rules_json JSON NOT NULL,
  status VARCHAR(32) NOT NULL,
  approved_decision_id VARCHAR(36) NULL,
  valid_from VARCHAR(32) NOT NULL,
  valid_to VARCHAR(32) NULL,
  created_by_party_id VARCHAR(36) NOT NULL,
  created_at VARCHAR(32) NOT NULL,
  approved_at VARCHAR(32) NULL,
  CONSTRAINT fk_functional_version_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_functional_version_definition FOREIGN KEY (functional_definition_id) REFERENCES functional_definitions(id),
  CONSTRAINT fk_functional_version_decision FOREIGN KEY (approved_decision_id) REFERENCES work_decisions(id),
  CONSTRAINT fk_functional_version_creator FOREIGN KEY (created_by_party_id) REFERENCES parties(id),
  UNIQUE KEY uq_functional_definition_version (tenant_id, functional_definition_id, version_no),
  INDEX idx_functional_version_status (tenant_id, functional_definition_id, status, valid_from)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE function_job_relationships (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  functional_definition_id VARCHAR(36) NOT NULL,
  job_profile_id VARCHAR(36) NOT NULL,
  relationship_type VARCHAR(32) NOT NULL,
  responsibility_summary TEXT NULL,
  status VARCHAR(32) NOT NULL,
  valid_from VARCHAR(32) NOT NULL,
  valid_to VARCHAR(32) NULL,
  created_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_function_job_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_function_job_function FOREIGN KEY (functional_definition_id) REFERENCES functional_definitions(id),
  CONSTRAINT fk_function_job_job FOREIGN KEY (job_profile_id) REFERENCES job_profiles(id),
  UNIQUE KEY uq_function_job_relationship
    (tenant_id, functional_definition_id, job_profile_id, relationship_type),
  INDEX idx_function_job_job (tenant_id, job_profile_id, relationship_type, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE functional_changes (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  functional_definition_id VARCHAR(36) NOT NULL,
  change_reference VARCHAR(191) NOT NULL,
  from_version_id VARCHAR(36) NULL,
  proposed_version_id VARCHAR(36) NULL,
  change_type VARCHAR(64) NOT NULL,
  reason TEXT NOT NULL,
  impact_summary TEXT NULL,
  status VARCHAR(32) NOT NULL,
  decision_id VARCHAR(36) NULL,
  implemented_at VARCHAR(32) NULL,
  verified_by_party_id VARCHAR(36) NULL,
  verified_at VARCHAR(32) NULL,
  created_by_party_id VARCHAR(36) NOT NULL,
  created_at VARCHAR(32) NOT NULL,
  updated_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_functional_change_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_functional_change_definition FOREIGN KEY (functional_definition_id) REFERENCES functional_definitions(id),
  CONSTRAINT fk_functional_change_from_version FOREIGN KEY (from_version_id) REFERENCES functional_definition_versions(id),
  CONSTRAINT fk_functional_change_proposed_version FOREIGN KEY (proposed_version_id) REFERENCES functional_definition_versions(id),
  CONSTRAINT fk_functional_change_decision FOREIGN KEY (decision_id) REFERENCES work_decisions(id),
  CONSTRAINT fk_functional_change_verifier FOREIGN KEY (verified_by_party_id) REFERENCES parties(id),
  CONSTRAINT fk_functional_change_creator FOREIGN KEY (created_by_party_id) REFERENCES parties(id),
  UNIQUE KEY uq_functional_change_reference (tenant_id, change_reference),
  INDEX idx_functional_change_status (tenant_id, functional_definition_id, status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE deployment_requirements (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  functional_definition_id VARCHAR(36) NOT NULL,
  functional_version_id VARCHAR(36) NOT NULL,
  required_job_profile_id VARCHAR(36) NULL,
  requirement_reference VARCHAR(191) NOT NULL,
  context_type VARCHAR(64) NOT NULL,
  context_id VARCHAR(191) NOT NULL,
  responsibility_scope TEXT NOT NULL,
  required_capacity_fte DECIMAL(7,4) NULL,
  required_from VARCHAR(32) NOT NULL,
  required_to VARCHAR(32) NULL,
  status VARCHAR(32) NOT NULL,
  version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_by_party_id VARCHAR(36) NOT NULL,
  created_at VARCHAR(32) NOT NULL,
  updated_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_deployment_requirement_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_deployment_requirement_function FOREIGN KEY (functional_definition_id) REFERENCES functional_definitions(id),
  CONSTRAINT fk_deployment_requirement_version FOREIGN KEY (functional_version_id) REFERENCES functional_definition_versions(id),
  CONSTRAINT fk_deployment_requirement_job FOREIGN KEY (required_job_profile_id) REFERENCES job_profiles(id),
  CONSTRAINT fk_deployment_requirement_creator FOREIGN KEY (created_by_party_id) REFERENCES parties(id),
  UNIQUE KEY uq_deployment_requirement_reference (tenant_id, requirement_reference),
  INDEX idx_deployment_requirement_context (tenant_id, context_type, context_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE functional_deployments (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  functional_definition_id VARCHAR(36) NOT NULL,
  functional_version_id VARCHAR(36) NOT NULL,
  deployment_requirement_id VARCHAR(36) NULL,
  deployment_reference VARCHAR(191) NOT NULL,
  delivery_organisation_party_id VARCHAR(36) NULL,
  organisation_unit_id VARCHAR(36) NULL,
  context_type VARCHAR(64) NOT NULL,
  context_id VARCHAR(191) NOT NULL,
  responsibility_scope TEXT NOT NULL,
  status VARCHAR(32) NOT NULL,
  version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  valid_from VARCHAR(32) NOT NULL,
  valid_to VARCHAR(32) NULL,
  created_by_party_id VARCHAR(36) NOT NULL,
  created_at VARCHAR(32) NOT NULL,
  updated_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_functional_deployment_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_functional_deployment_function FOREIGN KEY (functional_definition_id) REFERENCES functional_definitions(id),
  CONSTRAINT fk_functional_deployment_version FOREIGN KEY (functional_version_id) REFERENCES functional_definition_versions(id),
  CONSTRAINT fk_functional_deployment_requirement FOREIGN KEY (deployment_requirement_id) REFERENCES deployment_requirements(id),
  CONSTRAINT fk_functional_deployment_org FOREIGN KEY (delivery_organisation_party_id) REFERENCES organisations(party_id),
  CONSTRAINT fk_functional_deployment_org_unit FOREIGN KEY (organisation_unit_id) REFERENCES organisation_units(id),
  CONSTRAINT fk_functional_deployment_creator FOREIGN KEY (created_by_party_id) REFERENCES parties(id),
  UNIQUE KEY uq_functional_deployment_reference (tenant_id, deployment_reference),
  INDEX idx_functional_deployment_context (tenant_id, context_type, context_id, status),
  INDEX idx_functional_deployment_function (tenant_id, functional_definition_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE deployment_assignments (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  functional_deployment_id VARCHAR(36) NOT NULL,
  job_profile_id VARCHAR(36) NOT NULL,
  position_id VARCHAR(36) NULL,
  person_party_id VARCHAR(36) NULL,
  organisation_party_id VARCHAR(36) NULL,
  assignment_role VARCHAR(32) NOT NULL,
  responsibility_scope TEXT NULL,
  allocation_percent DECIMAL(7,4) NOT NULL DEFAULT 100.0000,
  authority_reference_type VARCHAR(64) NULL,
  authority_reference_id VARCHAR(191) NULL,
  status VARCHAR(32) NOT NULL,
  valid_from VARCHAR(32) NOT NULL,
  valid_to VARCHAR(32) NULL,
  created_by_party_id VARCHAR(36) NOT NULL,
  created_at VARCHAR(32) NOT NULL,
  updated_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_deployment_assignment_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_deployment_assignment_deployment FOREIGN KEY (functional_deployment_id) REFERENCES functional_deployments(id),
  CONSTRAINT fk_deployment_assignment_job FOREIGN KEY (job_profile_id) REFERENCES job_profiles(id),
  CONSTRAINT fk_deployment_assignment_position FOREIGN KEY (position_id) REFERENCES positions(id),
  CONSTRAINT fk_deployment_assignment_person FOREIGN KEY (person_party_id) REFERENCES persons(party_id),
  CONSTRAINT fk_deployment_assignment_org FOREIGN KEY (organisation_party_id) REFERENCES organisations(party_id),
  CONSTRAINT fk_deployment_assignment_creator FOREIGN KEY (created_by_party_id) REFERENCES parties(id),
  INDEX idx_deployment_assignment_deployment
    (tenant_id, functional_deployment_id, status, valid_from, valid_to),
  INDEX idx_deployment_assignment_person
    (tenant_id, person_party_id, status, valid_from, valid_to),
  INDEX idx_deployment_assignment_position
    (tenant_id, position_id, status, valid_from, valid_to)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
