-- NuBlox V3 MySQL
-- 0039: managed deliverable requirement and delivery runtime.
-- Connects governed functional deployment and Job/Position responsibility to actual enterprise outputs.
-- Controlled drawing/model/document representations continue to use AGG-07-INFORMATION.

CREATE TABLE deliverable_requirements (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  requirement_ref VARCHAR(191) NOT NULL,
  title VARCHAR(500) NOT NULL,
  description TEXT NULL,
  requirement_source_type VARCHAR(64) NOT NULL,
  requirement_source_id VARCHAR(191) NOT NULL,
  context_type VARCHAR(64) NOT NULL,
  context_id VARCHAR(191) NOT NULL,
  functional_definition_id VARCHAR(36) NULL,
  functional_deployment_id VARCHAR(36) NULL,
  required_job_profile_id VARCHAR(36) NULL,
  deliverable_type VARCHAR(128) NOT NULL,
  output_kind VARCHAR(64) NOT NULL,
  authoring_mode VARCHAR(32) NOT NULL,
  discipline_code VARCHAR(64) NULL,
  classification_code VARCHAR(191) NULL,
  review_required BOOLEAN NOT NULL DEFAULT TRUE,
  approval_required BOOLEAN NOT NULL DEFAULT TRUE,
  acceptance_required BOOLEAN NOT NULL DEFAULT FALSE,
  planned_start_at VARCHAR(32) NULL,
  planned_issue_at VARCHAR(32) NULL,
  required_acceptance_at VARCHAR(32) NULL,
  status VARCHAR(32) NOT NULL,
  version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_by_party_id VARCHAR(36) NOT NULL,
  created_at VARCHAR(32) NOT NULL,
  updated_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_deliverable_requirement_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_deliverable_requirement_function FOREIGN KEY (functional_definition_id) REFERENCES functional_definitions(id),
  CONSTRAINT fk_deliverable_requirement_deployment FOREIGN KEY (functional_deployment_id) REFERENCES functional_deployments(id),
  CONSTRAINT fk_deliverable_requirement_job FOREIGN KEY (required_job_profile_id) REFERENCES job_profiles(id),
  CONSTRAINT fk_deliverable_requirement_creator FOREIGN KEY (created_by_party_id) REFERENCES parties(id),
  UNIQUE KEY uq_deliverable_requirement_ref (tenant_id, requirement_ref),
  INDEX idx_deliverable_requirement_context (tenant_id, context_type, context_id, status, planned_issue_at),
  INDEX idx_deliverable_requirement_function (tenant_id, functional_definition_id, functional_deployment_id, status),
  INDEX idx_deliverable_requirement_job (tenant_id, required_job_profile_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE deliverable_items (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  deliverable_ref VARCHAR(191) NOT NULL,
  requirement_id VARCHAR(36) NOT NULL,
  title VARCHAR(500) NOT NULL,
  responsible_deployment_assignment_id VARCHAR(36) NULL,
  responsible_position_id VARCHAR(36) NULL,
  responsible_party_id VARCHAR(36) NULL,
  originating_organisation_party_id VARCHAR(36) NULL,
  information_container_id VARCHAR(36) NULL,
  managed_object_type VARCHAR(128) NULL,
  managed_object_id VARCHAR(191) NULL,
  current_revision_label VARCHAR(64) NULL,
  status VARCHAR(32) NOT NULL,
  version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  workflow_instance_id VARCHAR(36) NULL,
  work_item_id VARCHAR(36) NULL,
  due_at VARCHAR(32) NULL,
  accepted_at VARCHAR(32) NULL,
  supersedes_deliverable_item_id VARCHAR(36) NULL,
  created_by_party_id VARCHAR(36) NOT NULL,
  created_at VARCHAR(32) NOT NULL,
  updated_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_deliverable_item_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_deliverable_item_requirement FOREIGN KEY (requirement_id) REFERENCES deliverable_requirements(id),
  CONSTRAINT fk_deliverable_item_assignment FOREIGN KEY (responsible_deployment_assignment_id) REFERENCES deployment_assignments(id),
  CONSTRAINT fk_deliverable_item_position FOREIGN KEY (responsible_position_id) REFERENCES positions(id),
  CONSTRAINT fk_deliverable_item_party FOREIGN KEY (responsible_party_id) REFERENCES parties(id),
  CONSTRAINT fk_deliverable_item_org FOREIGN KEY (originating_organisation_party_id) REFERENCES organisations(party_id),
  CONSTRAINT fk_deliverable_item_information FOREIGN KEY (information_container_id) REFERENCES information_containers(id),
  CONSTRAINT fk_deliverable_item_workflow FOREIGN KEY (workflow_instance_id) REFERENCES workflow_instances(id),
  CONSTRAINT fk_deliverable_item_work_item FOREIGN KEY (work_item_id) REFERENCES work_items(id),
  CONSTRAINT fk_deliverable_item_supersedes FOREIGN KEY (supersedes_deliverable_item_id) REFERENCES deliverable_items(id),
  CONSTRAINT fk_deliverable_item_creator FOREIGN KEY (created_by_party_id) REFERENCES parties(id),
  UNIQUE KEY uq_deliverable_item_ref (tenant_id, deliverable_ref),
  INDEX idx_deliverable_item_requirement (tenant_id, requirement_id, status),
  INDEX idx_deliverable_item_responsible (tenant_id, responsible_party_id, status, due_at),
  INDEX idx_deliverable_item_position (tenant_id, responsible_position_id, status, due_at),
  INDEX idx_deliverable_item_work (tenant_id, work_item_id),
  INDEX idx_deliverable_item_information (tenant_id, information_container_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE deliverable_participants (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  deliverable_item_id VARCHAR(36) NOT NULL,
  participant_role VARCHAR(32) NOT NULL,
  party_id VARCHAR(36) NULL,
  position_id VARCHAR(36) NULL,
  organisation_party_id VARCHAR(36) NULL,
  deployment_assignment_id VARCHAR(36) NULL,
  status VARCHAR(32) NOT NULL,
  valid_from VARCHAR(32) NOT NULL,
  valid_to VARCHAR(32) NULL,
  created_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_deliverable_participant_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_deliverable_participant_item FOREIGN KEY (deliverable_item_id) REFERENCES deliverable_items(id),
  CONSTRAINT fk_deliverable_participant_party FOREIGN KEY (party_id) REFERENCES parties(id),
  CONSTRAINT fk_deliverable_participant_position FOREIGN KEY (position_id) REFERENCES positions(id),
  CONSTRAINT fk_deliverable_participant_org FOREIGN KEY (organisation_party_id) REFERENCES organisations(party_id),
  CONSTRAINT fk_deliverable_participant_deployment FOREIGN KEY (deployment_assignment_id) REFERENCES deployment_assignments(id),
  INDEX idx_deliverable_participant_item (tenant_id, deliverable_item_id, participant_role, status),
  INDEX idx_deliverable_participant_party (tenant_id, party_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE deliverable_issues (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  deliverable_item_id VARCHAR(36) NOT NULL,
  issue_ref VARCHAR(191) NOT NULL,
  issue_type VARCHAR(64) NOT NULL,
  information_revision_id VARCHAR(36) NULL,
  revision_label VARCHAR(64) NULL,
  purpose_of_issue VARCHAR(128) NULL,
  suitability_code VARCHAR(64) NULL,
  issued_by_party_id VARCHAR(36) NOT NULL,
  issued_at VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_deliverable_issue_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_deliverable_issue_item FOREIGN KEY (deliverable_item_id) REFERENCES deliverable_items(id),
  CONSTRAINT fk_deliverable_issue_revision FOREIGN KEY (information_revision_id) REFERENCES information_revisions(id),
  CONSTRAINT fk_deliverable_issue_actor FOREIGN KEY (issued_by_party_id) REFERENCES parties(id),
  UNIQUE KEY uq_deliverable_issue_ref (tenant_id, issue_ref),
  INDEX idx_deliverable_issue_item (tenant_id, deliverable_item_id, issued_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE deliverable_issue_recipients (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  deliverable_issue_id VARCHAR(36) NOT NULL,
  recipient_party_id VARCHAR(36) NOT NULL,
  recipient_role VARCHAR(64) NULL,
  response_status VARCHAR(32) NOT NULL,
  response_decision_id VARCHAR(36) NULL,
  response_note TEXT NULL,
  responded_at VARCHAR(32) NULL,
  created_at VARCHAR(32) NOT NULL,
  updated_at VARCHAR(32) NOT NULL,
  CONSTRAINT fk_deliverable_recipient_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_deliverable_recipient_issue FOREIGN KEY (deliverable_issue_id) REFERENCES deliverable_issues(id),
  CONSTRAINT fk_deliverable_recipient_party FOREIGN KEY (recipient_party_id) REFERENCES parties(id),
  CONSTRAINT fk_deliverable_recipient_decision FOREIGN KEY (response_decision_id) REFERENCES work_decisions(id),
  UNIQUE KEY uq_deliverable_issue_recipient (deliverable_issue_id, recipient_party_id),
  INDEX idx_deliverable_recipient_status (tenant_id, response_status, responded_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
