import { createHash } from 'node:crypto';
import {
  createControlCharacteristic,
  createManufacturingOperation,
  createManufacturingProcessPlan,
  createManufacturingResource,
  createManufacturingResourceAllocation,
  createManufacturingSequenceLink,
  freezeManufacturingProcessPlan,
  releaseManufacturingProcessPlan,
  type CanonicalObjectIdentity,
  type ControlCharacteristic,
  type Decision,
  type ManufacturingOperation,
  type ManufacturingProcessPlan,
  type ManufacturingResource,
  type ManufacturingResourceAllocation,
  type ManufacturingSequenceLink,
  type Person,
  type TenantId
} from '@nublox/kernel';
import type { Pool,PoolConnection,ResultSetHeader,RowDataPacket } from 'mysql2/promise';
import { withTransaction } from './database.js';
import { writeOutboxEvent } from './platform-writes.js';
import type { AuditContext } from './repository.js';

interface PlanRow extends RowDataPacket{
 id:string;tenant_id:string;scope_object_id:string;code:string;name:string;version:number;status:ManufacturingProcessPlan['status'];
 description:string|null;plant_reference:string|null;checksum:string|null;created_by_person_id:string;plan_created_at:Date;
 frozen_by_person_id:string|null;frozen_at:Date|null;release_decision_id:string|null;released_at:Date|null;row_version:number;
}
interface OperationRow extends RowDataPacket{
 id:string;tenant_id:string;process_plan_id:string;operation_number:string;name:string;operation_type:ManufacturingOperation['operationType'];
 description:string|null;setup_minutes:string|number;run_minutes:string|number;yield_percent:string|number;work_instructions:string|Record<string,unknown>|null;
}
interface SequenceRow extends RowDataPacket{
 id:string;tenant_id:string;process_plan_id:string;predecessor_operation_id:string;successor_operation_id:string;
 sequence_type:ManufacturingSequenceLink['sequenceType'];lag_minutes:string|number;
}
interface ResourceRow extends RowDataPacket{
 id:string;tenant_id:string;code:string;name:string;resource_type:ManufacturingResource['resourceType'];description:string|null;
 capacity_unit:string|null;capacity_per_day:string|number|null;effective_from:Date|null;effective_to:Date|null;status:ManufacturingResource['status'];
}
interface AllocationRow extends RowDataPacket{
 id:string;tenant_id:string;operation_id:string;resource_id:string;quantity:string|number;usage_unit:string;required:number;
}
interface CharacteristicRow extends RowDataPacket{
 id:string;tenant_id:string;scope_object_id:string;operation_id:string|null;code:string;name:string;
 characteristic_type:ControlCharacteristic['characteristicType'];severity:ControlCharacteristic['severity'];unit:string|null;
 nominal_value:string|number|null;lower_limit:string|number|null;upper_limit:string|number|null;specification:string|null;
 sampling_plan:string|Record<string,unknown>|null;effective_from:Date|null;effective_to:Date|null;status:ControlCharacteristic['status'];
}
interface PersonRow extends RowDataPacket{id:string;tenant_id:string;party_id:string;legal_name:string;preferred_name:string|null;status:Person['status'];}
interface DecisionRow extends RowDataPacket{id:string;tenant_id:string;decision_type:string;subject_object_id:string;subject_version:string|null;outcome:string;reason:string;decider_person_id:string;authority_grant_id:string|null;decided_at:Date;}
interface ObjectRow extends RowDataPacket{id:string;tenant_id:string;object_type:string;stable_key:string;created_at:Date;}

function objectJson(v:unknown){if(v===null)return undefined;const p=typeof v==='string'?JSON.parse(v):v;return typeof p==='object'&&p!==null&&!Array.isArray(p)?p as Readonly<Record<string,unknown>>:undefined;}
function stable(v:unknown):unknown{if(Array.isArray(v))return v.map(stable);if(typeof v==='object'&&v!==null){const o=v as Record<string,unknown>;return Object.fromEntries(Object.keys(o).sort().map(k=>[k,stable(o[k])]));}return v;}
function sha(v:unknown){return 'sha256:'+createHash('sha256').update(JSON.stringify(stable(v))).digest('hex');}
const mapPlan=(r:PlanRow):ManufacturingProcessPlan=>({id:r.id as ManufacturingProcessPlan['id'],tenantId:r.tenant_id as TenantId,scopeObjectId:r.scope_object_id as ManufacturingProcessPlan['scopeObjectId'],code:r.code,name:r.name,version:Number(r.version),status:r.status,...(r.description?{description:r.description}:{}),...(r.plant_reference?{plantReference:r.plant_reference}:{}),...(r.checksum?{checksum:r.checksum}:{}),createdByPersonId:r.created_by_person_id as ManufacturingProcessPlan['createdByPersonId'],createdAt:r.plan_created_at.toISOString(),...(r.frozen_by_person_id?{frozenByPersonId:r.frozen_by_person_id as NonNullable<ManufacturingProcessPlan['frozenByPersonId']>}:{}),...(r.frozen_at?{frozenAt:r.frozen_at.toISOString()}:{}),...(r.release_decision_id?{releaseDecisionId:r.release_decision_id as NonNullable<ManufacturingProcessPlan['releaseDecisionId']>}:{}),...(r.released_at?{releasedAt:r.released_at.toISOString()}:{})});
const mapOperation=(r:OperationRow):ManufacturingOperation=>({id:r.id as ManufacturingOperation['id'],tenantId:r.tenant_id as TenantId,processPlanId:r.process_plan_id as ManufacturingOperation['processPlanId'],operationNumber:r.operation_number,name:r.name,operationType:r.operation_type,...(r.description?{description:r.description}:{}),setupMinutes:Number(r.setup_minutes),runMinutes:Number(r.run_minutes),yieldPercent:Number(r.yield_percent),...(objectJson(r.work_instructions)?{workInstructions:objectJson(r.work_instructions)!}:{})});
const mapSequence=(r:SequenceRow):ManufacturingSequenceLink=>({id:r.id as ManufacturingSequenceLink['id'],tenantId:r.tenant_id as TenantId,processPlanId:r.process_plan_id as ManufacturingSequenceLink['processPlanId'],predecessorOperationId:r.predecessor_operation_id as ManufacturingSequenceLink['predecessorOperationId'],successorOperationId:r.successor_operation_id as ManufacturingSequenceLink['successorOperationId'],sequenceType:r.sequence_type,lagMinutes:Number(r.lag_minutes)});
const mapResource=(r:ResourceRow):ManufacturingResource=>({id:r.id as ManufacturingResource['id'],tenantId:r.tenant_id as TenantId,code:r.code,name:r.name,resourceType:r.resource_type,...(r.description?{description:r.description}:{}),...(r.capacity_unit?{capacityUnit:r.capacity_unit}:{}),...(r.capacity_per_day!==null?{capacityPerDay:Number(r.capacity_per_day)}:{}),...(r.effective_from?{effectiveFrom:r.effective_from.toISOString()}:{}),...(r.effective_to?{effectiveTo:r.effective_to.toISOString()}:{}),status:r.status});
const mapAllocation=(r:AllocationRow):ManufacturingResourceAllocation=>({id:r.id as ManufacturingResourceAllocation['id'],tenantId:r.tenant_id as TenantId,operationId:r.operation_id as ManufacturingResourceAllocation['operationId'],resourceId:r.resource_id as ManufacturingResourceAllocation['resourceId'],quantity:Number(r.quantity),usageUnit:r.usage_unit,required:Boolean(r.required)});
const mapCharacteristic=(r:CharacteristicRow):ControlCharacteristic=>({id:r.id as ControlCharacteristic['id'],tenantId:r.tenant_id as TenantId,scopeObjectId:r.scope_object_id as ControlCharacteristic['scopeObjectId'],...(r.operation_id?{operationId:r.operation_id as NonNullable<ControlCharacteristic['operationId']>}:{}),code:r.code,name:r.name,characteristicType:r.characteristic_type,severity:r.severity,...(r.unit?{unit:r.unit}:{}),...(r.nominal_value!==null?{nominalValue:Number(r.nominal_value)}:{}),...(r.lower_limit!==null?{lowerLimit:Number(r.lower_limit)}:{}),...(r.upper_limit!==null?{upperLimit:Number(r.upper_limit)}:{}),...(r.specification?{specification:r.specification}:{}),...(objectJson(r.sampling_plan)?{samplingPlan:objectJson(r.sampling_plan)!}:{}),...(r.effective_from?{effectiveFrom:r.effective_from.toISOString()}:{}),...(r.effective_to?{effectiveTo:r.effective_to.toISOString()}:{}),status:r.status});
const mapPerson=(r:PersonRow):Person=>({id:r.id as Person['id'],tenantId:r.tenant_id as TenantId,partyId:r.party_id as Person['partyId'],legalName:r.legal_name,...(r.preferred_name?{preferredName:r.preferred_name}:{}),status:r.status});
const mapDecision=(r:DecisionRow):Decision=>({id:r.id as Decision['id'],tenantId:r.tenant_id as TenantId,decisionType:r.decision_type,subjectObjectId:r.subject_object_id as Decision['subjectObjectId'],...(r.subject_version?{subjectVersion:r.subject_version}:{}),outcome:r.outcome,reason:r.reason,deciderPersonId:r.decider_person_id as Decision['deciderPersonId'],...(r.authority_grant_id?{authorityGrantId:r.authority_grant_id as NonNullable<Decision['authorityGrantId']>}:{}),decidedAt:r.decided_at.toISOString()});
const mapObject=(r:ObjectRow):CanonicalObjectIdentity=>({id:r.id as CanonicalObjectIdentity['id'],tenantId:r.tenant_id as TenantId,objectType:r.object_type,stableKey:r.stable_key,createdAt:r.created_at.toISOString()});
async function evidence(c:PoolConnection,t:TenantId,type:string,id:string,action:string,audit:AuditContext,payload:unknown){await c.execute('INSERT INTO kernel_audit_entries (tenant_id,entity_type,entity_id,action,actor_person_id,correlation_id,payload) VALUES (?,?,?,?,?,?,?)',[t,type,id,action,audit.actorPersonId??null,audit.correlationId??null,JSON.stringify(payload)]);await writeOutboxEvent(c,{tenantId:t,aggregateType:type,aggregateId:id,eventType:type+'.'+action,payload});}

export class MySqlManufacturingRepository{
 constructor(private readonly pool:Pool){}
 async createProcessPlan(input:ManufacturingProcessPlan,audit:AuditContext={}){
  const [scope,creator]=await Promise.all([this.requireObject(input.tenantId,input.scopeObjectId),this.requirePerson(input.tenantId,input.createdByPersonId)]);
  createManufacturingProcessPlan(input,scope,creator);
  await withTransaction(this.pool,async c=>{await c.execute('INSERT INTO manufacturing_process_plans (id,tenant_id,scope_object_id,code,name,version,status,description,plant_reference,checksum,created_by_person_id,plan_created_at,frozen_by_person_id,frozen_at,release_decision_id,released_at,active_guard_key,updated_by_person_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[input.id,input.tenantId,input.scopeObjectId,input.code,input.name,input.version,input.status,input.description??null,input.plantReference??null,null,input.createdByPersonId,new Date(input.createdAt),null,null,null,null,null,audit.actorPersonId??null]);await evidence(c,input.tenantId,'MANUFACTURING_PROCESS_PLAN',input.id,'CREATED',audit,input);});
 }
 async addOperation(input:ManufacturingOperation,audit:AuditContext={}){
  const plan=await this.requirePlan(input.tenantId,input.processPlanId);createManufacturingOperation(input,plan);
  await withTransaction(this.pool,async c=>{await c.execute('INSERT INTO manufacturing_operations (id,tenant_id,process_plan_id,operation_number,name,operation_type,description,setup_minutes,run_minutes,yield_percent,work_instructions) VALUES (?,?,?,?,?,?,?,?,?,?,?)',[input.id,input.tenantId,input.processPlanId,input.operationNumber,input.name,input.operationType,input.description??null,input.setupMinutes,input.runMinutes,input.yieldPercent,input.workInstructions?JSON.stringify(input.workInstructions):null]);await evidence(c,input.tenantId,'MANUFACTURING_OPERATION',input.id,'CREATED',audit,input);});
 }
 async addSequence(input:ManufacturingSequenceLink,audit:AuditContext={}){
  const [plan,pred,succ]=await Promise.all([this.requirePlan(input.tenantId,input.processPlanId),this.requireOperation(input.tenantId,input.predecessorOperationId),this.requireOperation(input.tenantId,input.successorOperationId)]);createManufacturingSequenceLink(input,plan,pred,succ);
  await withTransaction(this.pool,async c=>{await c.execute('INSERT INTO manufacturing_sequence_links (id,tenant_id,process_plan_id,predecessor_operation_id,successor_operation_id,sequence_type,lag_minutes) VALUES (?,?,?,?,?,?,?)',[input.id,input.tenantId,input.processPlanId,input.predecessorOperationId,input.successorOperationId,input.sequenceType,input.lagMinutes]);await evidence(c,input.tenantId,'MANUFACTURING_SEQUENCE_LINK',input.id,'CREATED',audit,input);});
 }
 async createResource(input:ManufacturingResource,audit:AuditContext={}){createManufacturingResource(input);await withTransaction(this.pool,async c=>{await c.execute('INSERT INTO manufacturing_resources (id,tenant_id,code,name,resource_type,description,capacity_unit,capacity_per_day,effective_from,effective_to,status) VALUES (?,?,?,?,?,?,?,?,?,?,?)',[input.id,input.tenantId,input.code,input.name,input.resourceType,input.description??null,input.capacityUnit??null,input.capacityPerDay??null,input.effectiveFrom?new Date(input.effectiveFrom):null,input.effectiveTo?new Date(input.effectiveTo):null,input.status]);await evidence(c,input.tenantId,'MANUFACTURING_RESOURCE',input.id,'CREATED',audit,input);});}
 async allocateResource(input:ManufacturingResourceAllocation,audit:AuditContext={}){const [op,res]=await Promise.all([this.requireOperation(input.tenantId,input.operationId),this.requireResource(input.tenantId,input.resourceId)]);createManufacturingResourceAllocation(input,op,res);const plan=await this.requirePlan(input.tenantId,op.processPlanId);if(plan.status!=='DRAFT')throw new Error('Resource Allocations can only be changed on a DRAFT Process Plan.');await withTransaction(this.pool,async c=>{await c.execute('INSERT INTO manufacturing_resource_allocations (id,tenant_id,operation_id,resource_id,quantity,usage_unit,required) VALUES (?,?,?,?,?,?,?)',[input.id,input.tenantId,input.operationId,input.resourceId,input.quantity,input.usageUnit,input.required]);await evidence(c,input.tenantId,'MANUFACTURING_RESOURCE_ALLOCATION',input.id,'CREATED',audit,input);});}
 async createCharacteristic(input:ControlCharacteristic,audit:AuditContext={}){const [scope,op]=await Promise.all([this.requireObject(input.tenantId,input.scopeObjectId),input.operationId?this.requireOperation(input.tenantId,input.operationId):Promise.resolve(undefined)]);if(op){const plan=await this.requirePlan(input.tenantId,op.processPlanId);if(plan.status!=='DRAFT')throw new Error('Operation Control Characteristics can only be changed on a DRAFT Process Plan.');}createControlCharacteristic(input,scope,op);await withTransaction(this.pool,async c=>{await c.execute('INSERT INTO manufacturing_control_characteristics (id,tenant_id,scope_object_id,operation_id,code,name,characteristic_type,severity,unit,nominal_value,lower_limit,upper_limit,specification,sampling_plan,effective_from,effective_to,status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[input.id,input.tenantId,input.scopeObjectId,input.operationId??null,input.code,input.name,input.characteristicType,input.severity,input.unit??null,input.nominalValue??null,input.lowerLimit??null,input.upperLimit??null,input.specification??null,input.samplingPlan?JSON.stringify(input.samplingPlan):null,input.effectiveFrom?new Date(input.effectiveFrom):null,input.effectiveTo?new Date(input.effectiveTo):null,input.status]);await evidence(c,input.tenantId,'CONTROL_CHARACTERISTIC',input.id,'CREATED',audit,input);});}
 async freezePlan(t:TenantId,id:ManufacturingProcessPlan['id'],freezerId:Person['id'],frozenAt:string,audit:AuditContext={}):Promise<ManufacturingProcessPlan>{
  return withTransaction(this.pool,async c=>{const [rows]=await c.execute<PlanRow[]>('SELECT * FROM manufacturing_process_plans WHERE tenant_id=? AND id=? FOR UPDATE',[t,id]);if(!rows[0])throw new Error('Manufacturing Process Plan not found in tenant.');const current=mapPlan(rows[0]);const [ops,seqs,allocs,chars,personRows]=await Promise.all([c.execute<OperationRow[]>('SELECT * FROM manufacturing_operations WHERE tenant_id=? AND process_plan_id=? ORDER BY operation_number,id',[t,id]),c.execute<SequenceRow[]>('SELECT * FROM manufacturing_sequence_links WHERE tenant_id=? AND process_plan_id=? ORDER BY predecessor_operation_id,successor_operation_id,id',[t,id]),c.execute<AllocationRow[]>('SELECT a.* FROM manufacturing_resource_allocations a JOIN manufacturing_operations o ON o.tenant_id=a.tenant_id AND o.id=a.operation_id WHERE a.tenant_id=? AND o.process_plan_id=? ORDER BY a.operation_id,a.resource_id',[t,id]),c.execute<CharacteristicRow[]>('SELECT c.* FROM manufacturing_control_characteristics c LEFT JOIN manufacturing_operations o ON o.tenant_id=c.tenant_id AND o.id=c.operation_id WHERE c.tenant_id=? AND (o.process_plan_id=? OR (c.operation_id IS NULL AND c.scope_object_id=?)) ORDER BY c.code,id',[t,id,current.scopeObjectId]),c.execute<PersonRow[]>('SELECT id,tenant_id,party_id,legal_name,preferred_name,status FROM persons WHERE tenant_id=? AND id=?',[t,freezerId])]);if(!personRows[0][0])throw new Error('Person not found in tenant.');const operations=ops[0].map(mapOperation),sequences=seqs[0].map(mapSequence),allocations=allocs[0].map(mapAllocation),characteristics=chars[0].map(mapCharacteristic);const checksum=sha({scopeObjectId:current.scopeObjectId,code:current.code,version:current.version,operations,sequences,allocations,characteristics});const next=freezeManufacturingProcessPlan(current,operations,sequences,allocations,characteristics,checksum,mapPerson(personRows[0][0]),frozenAt);const [u]=await c.execute<ResultSetHeader>('UPDATE manufacturing_process_plans SET status=?,checksum=?,frozen_by_person_id=?,frozen_at=?,updated_by_person_id=?,row_version=row_version+1 WHERE tenant_id=? AND id=? AND row_version=?',[next.status,next.checksum!,next.frozenByPersonId!,new Date(frozenAt),audit.actorPersonId??null,t,id,rows[0].row_version]);if(u.affectedRows!==1)throw new Error('Concurrent Process Plan freeze detected.');await evidence(c,t,'MANUFACTURING_PROCESS_PLAN',id,'FROZEN',audit,next);return next;});
 }
 async releasePlan(t:TenantId,id:ManufacturingProcessPlan['id'],decisionId:Decision['id'],releasedAt:string,audit:AuditContext={}):Promise<ManufacturingProcessPlan>{
  return withTransaction(this.pool,async c=>{const [rows]=await c.execute<PlanRow[]>('SELECT * FROM manufacturing_process_plans WHERE tenant_id=? AND id=? FOR UPDATE',[t,id]);if(!rows[0])throw new Error('Manufacturing Process Plan not found in tenant.');const current=mapPlan(rows[0]);const decision=await this.requireDecision(t,decisionId,c);const next=releaseManufacturingProcessPlan(current,decision,releasedAt);await c.execute("UPDATE manufacturing_process_plans SET status='SUPERSEDED',active_guard_key=NULL,updated_by_person_id=?,row_version=row_version+1 WHERE tenant_id=? AND code=? AND status='RELEASED' AND id<>?",[audit.actorPersonId??null,t,current.code,id]);const [u]=await c.execute<ResultSetHeader>('UPDATE manufacturing_process_plans SET status=?,release_decision_id=?,released_at=?,active_guard_key=code,updated_by_person_id=?,row_version=row_version+1 WHERE tenant_id=? AND id=? AND row_version=?',[next.status,next.releaseDecisionId!,new Date(releasedAt),audit.actorPersonId??null,t,id,rows[0].row_version]);if(u.affectedRows!==1)throw new Error('Concurrent Process Plan release detected.');await evidence(c,t,'MANUFACTURING_PROCESS_PLAN',id,'RELEASED',audit,next);return next;});
 }
 async listPlans(t:TenantId){const [r]=await this.pool.execute<PlanRow[]>('SELECT * FROM manufacturing_process_plans WHERE tenant_id=? ORDER BY code,version DESC',[t]);return r.map(mapPlan);}
 async listOperations(t:TenantId){const [r]=await this.pool.execute<OperationRow[]>('SELECT * FROM manufacturing_operations WHERE tenant_id=? ORDER BY process_plan_id,operation_number,id',[t]);return r.map(mapOperation);}
 async listSequences(t:TenantId){const [r]=await this.pool.execute<SequenceRow[]>('SELECT * FROM manufacturing_sequence_links WHERE tenant_id=? ORDER BY process_plan_id,predecessor_operation_id,id',[t]);return r.map(mapSequence);}
 async listResources(t:TenantId){const [r]=await this.pool.execute<ResourceRow[]>('SELECT * FROM manufacturing_resources WHERE tenant_id=? ORDER BY code,id',[t]);return r.map(mapResource);}
 async listAllocations(t:TenantId){const [r]=await this.pool.execute<AllocationRow[]>('SELECT * FROM manufacturing_resource_allocations WHERE tenant_id=? ORDER BY operation_id,resource_id',[t]);return r.map(mapAllocation);}
 async listCharacteristics(t:TenantId){const [r]=await this.pool.execute<CharacteristicRow[]>('SELECT * FROM manufacturing_control_characteristics WHERE tenant_id=? ORDER BY code,id',[t]);return r.map(mapCharacteristic);}
 private async requirePlan(t:TenantId,id:string,c?:PoolConnection){const q=c??this.pool;const [r]=await q.execute<PlanRow[]>('SELECT * FROM manufacturing_process_plans WHERE tenant_id=? AND id=?',[t,id]);if(!r[0])throw new Error('Manufacturing Process Plan not found in tenant.');return mapPlan(r[0]);}
 private async requireOperation(t:TenantId,id:string,c?:PoolConnection){const q=c??this.pool;const [r]=await q.execute<OperationRow[]>('SELECT * FROM manufacturing_operations WHERE tenant_id=? AND id=?',[t,id]);if(!r[0])throw new Error('Manufacturing Operation not found in tenant.');return mapOperation(r[0]);}
 private async requireResource(t:TenantId,id:string,c?:PoolConnection){const q=c??this.pool;const [r]=await q.execute<ResourceRow[]>('SELECT * FROM manufacturing_resources WHERE tenant_id=? AND id=?',[t,id]);if(!r[0])throw new Error('Manufacturing Resource not found in tenant.');return mapResource(r[0]);}
 private async requirePerson(t:TenantId,id:string,c?:PoolConnection){const q=c??this.pool;const [r]=await q.execute<PersonRow[]>('SELECT id,tenant_id,party_id,legal_name,preferred_name,status FROM persons WHERE tenant_id=? AND id=?',[t,id]);if(!r[0])throw new Error('Person not found in tenant.');return mapPerson(r[0]);}
 private async requireDecision(t:TenantId,id:string,c?:PoolConnection){const q=c??this.pool;const [r]=await q.execute<DecisionRow[]>('SELECT * FROM decisions WHERE tenant_id=? AND id=?',[t,id]);if(!r[0])throw new Error('Decision not found in tenant.');return mapDecision(r[0]);}
 private async requireObject(t:TenantId,id:string,c?:PoolConnection){const q=c??this.pool;const [r]=await q.execute<ObjectRow[]>('SELECT id,tenant_id,object_type,stable_key,created_at FROM canonical_objects WHERE tenant_id=? AND id=?',[t,id]);if(!r[0])throw new Error('Canonical Object not found in tenant.');return mapObject(r[0]);}
}
