export const KERNEL_OBJECT_TYPES = [
  'TENANT',
  'PARTY',
  'PERSON',
  'ORGANISATION',
  'ORGANISATION_UNIT',
  'POSITION',
  'POSITION_OCCUPANCY',
  'JOB_PROFILE',
  'AUTHORITY_DEFINITION',
  'AUTHORITY_GRANT',
  'DELEGATION',
  'CANONICAL_RELATIONSHIP',
  'LIFECYCLE_DEFINITION',
  'LIFECYCLE_STATE_DEFINITION',
  'LIFECYCLE_TRANSITION_DEFINITION',
  'OBJECT_LIFECYCLE_STATE',
  'DECISION',
  'BUSINESS_EVENT',
  'EVIDENCE_RECORD'
] as const;

export type KernelObjectType = (typeof KERNEL_OBJECT_TYPES)[number];

export const KERNEL_RELATIONSHIP_TYPES = [
  'PARTY_SPECIALISES_AS_PERSON',
  'PARTY_SPECIALISES_AS_ORGANISATION',
  'ORGANISATION_CONTAINS_UNIT',
  'UNIT_CONTAINS_UNIT',
  'UNIT_HAS_POSITION',
  'POSITION_REFERENCES_JOB_PROFILE',
  'PERSON_OCCUPIES_POSITION',
  'AUTHORITY_GRANTED_TO',
  'AUTHORITY_DELEGATED_TO'
] as const;

export type KernelRelationshipType = (typeof KERNEL_RELATIONSHIP_TYPES)[number];
