import { fail,redirect } from '@sveltejs/kit';
import type { Actions,PageServerLoad } from './$types';
import { hasPermission } from '$lib/server/platform-context';
import { resolveRequestCommandContext } from '$lib/server/request-command-context';
import {
  addStrategicReviewFinding,completeStrategicReview,conveneStrategicReview,createStrategicReview,createStrategicReviewAction,
  listGovernanceMeetings,listMeetingActionIds,listMeetingAgenda,listMeetingAttendees,listMeetingDecisionIds,listStrategicReviewFindings,
  recordMeetingAttendance,recordStrategicReviewDecision
} from '$lib/server/strategic-review';

function text(data:FormData,name:string){const value=data.get(name);return typeof value==='string'?value.trim():'';}
function integer(data:FormData,name:string){const value=Number(text(data,name));if(!Number.isInteger(value)||value<1)throw new Error(name+' must be a positive whole number.');return value;}
function target(tenant:string,id?:string){return `/${tenant}/app/functions/f01/strategic-review${id?'?meeting='+encodeURIComponent(id):''}`;}
function problem(error:unknown){return fail(400,{message:error instanceof Error?error.message:'The Strategic Review command could not be completed.'});}
function attendees(data:FormData){return text(data,'attendees').split(/\r?\n/).map(row=>row.trim()).filter(Boolean).map((row,index)=>{const [partyId,attendanceRole]=row.split('|').map(x=>x.trim());if(!partyId||!attendanceRole)throw new Error('Attendee row '+(index+1)+' requires Party ID and role.');return{partyId,attendanceRole};});}
function agenda(data:FormData){return text(data,'agenda').split(/\r?\n/).map(row=>row.trim()).filter(Boolean).map((row,index)=>{const [subject,requiredOutcome,purpose,subjectType='',subjectId='',subjectVersion='']=row.split('|').map(x=>x.trim());if(!subject||!requiredOutcome||!purpose)throw new Error('Agenda row '+(index+1)+' requires subject, required outcome and purpose.');return{subject,requiredOutcome,purpose,subjectType:subjectType||undefined,subjectId:subjectId||undefined,subjectVersion:subjectVersion||undefined};});}

export const load:PageServerLoad=async({params,url,locals})=>{
  const context=await resolveRequestCommandContext(params.tenant,locals);const meetings=await listGovernanceMeetings(context);const selected=meetings.find(row=>row.id===url.searchParams.get('meeting'))??meetings[0]??null;
  const [attendeeRows,agendaRows,findings,decisions,actions]=selected?await Promise.all([listMeetingAttendees(context,selected.id),listMeetingAgenda(context,selected.id),listStrategicReviewFindings(context,selected.id),listMeetingDecisionIds(context,selected.id),listMeetingActionIds(context,selected.id)]):[[],[],[],[],[]];
  return{tenantSlug:params.tenant,meetings,selected,attendeeRows,agendaRows,findings,decisions,actions,actorPartyId:context.actorPartyId,capabilities:{canManage:hasPermission(context,'strategy.review.manage'),canConduct:hasPermission(context,'strategy.review.conduct')}};
};
export const actions:Actions={
  create:async({request,params,locals})=>{const data=await request.formData();try{const id=await createStrategicReview(await resolveRequestCommandContext(params.tenant,locals),{meetingRef:text(data,'meetingRef'),governanceContextType:text(data,'governanceContextType'),governanceContextId:text(data,'governanceContextId'),scheduledAt:text(data,'scheduledAt'),locationChannel:text(data,'locationChannel')||undefined,quorumRequired:integer(data,'quorumRequired'),attendees:attendees(data),agenda:agenda(data)});redirect(303,target(params.tenant,id));}catch(error){if(error&&typeof error==='object'&&'status'in error)throw error;return problem(error);}},
  attendance:async({request,params,locals})=>{const data=await request.formData();const id=text(data,'meetingId');try{await recordMeetingAttendance(await resolveRequestCommandContext(params.tenant,locals),id,text(data,'partyId'),text(data,'status') as 'PRESENT'|'ABSENT');redirect(303,target(params.tenant,id));}catch(error){if(error&&typeof error==='object'&&'status'in error)throw error;return problem(error);}},
  convene:async({request,params,locals})=>{const data=await request.formData();const id=text(data,'meetingId');try{await conveneStrategicReview(await resolveRequestCommandContext(params.tenant,locals),id,integer(data,'aggregateVersion'));redirect(303,target(params.tenant,id));}catch(error){if(error&&typeof error==='object'&&'status'in error)throw error;return problem(error);}},
  finding:async({request,params,locals})=>{const data=await request.formData();const id=text(data,'meetingId');try{await addStrategicReviewFinding(await resolveRequestCommandContext(params.tenant,locals),id,{findingType:text(data,'findingType'),subjectType:text(data,'subjectType'),subjectId:text(data,'subjectId'),subjectVersion:text(data,'subjectVersion')||undefined,finding:text(data,'finding'),recommendation:text(data,'recommendation')});redirect(303,target(params.tenant,id));}catch(error){if(error&&typeof error==='object'&&'status'in error)throw error;return problem(error);}},
  decision:async({request,params,locals})=>{const data=await request.formData();const id=text(data,'meetingId');try{await recordStrategicReviewDecision(await resolveRequestCommandContext(params.tenant,locals),id,{decisionType:'STRATEGIC_REVIEW_DECISION',subjectType:text(data,'subjectType'),subjectId:text(data,'subjectId'),subjectVersion:text(data,'subjectVersion')||undefined,outcome:text(data,'outcome'),reason:text(data,'reason')});redirect(303,target(params.tenant,id));}catch(error){if(error&&typeof error==='object'&&'status'in error)throw error;return problem(error);}},
  action:async({request,params,locals})=>{const data=await request.formData();const id=text(data,'meetingId');try{await createStrategicReviewAction(await resolveRequestCommandContext(params.tenant,locals),id,{title:text(data,'title'),instructions:text(data,'instructions'),subjectType:text(data,'subjectType')||undefined,subjectId:text(data,'subjectId')||undefined,subjectVersion:text(data,'subjectVersion')||undefined,priority:text(data,'priority')||undefined,dueAt:text(data,'dueAt')||undefined});redirect(303,target(params.tenant,id));}catch(error){if(error&&typeof error==='object'&&'status'in error)throw error;return problem(error);}},
  complete:async({request,params,locals})=>{const data=await request.formData();const id=text(data,'meetingId');try{await completeStrategicReview(await resolveRequestCommandContext(params.tenant,locals),id,integer(data,'aggregateVersion'),{minutesSummary:text(data,'minutesSummary'),nextReviewAt:text(data,'nextReviewAt')||undefined});redirect(303,target(params.tenant,id));}catch(error){if(error&&typeof error==='object'&&'status'in error)throw error;return problem(error);}}
};
